from enum import Enum


class SecurityEventType(str, Enum):
    AUTHENTICATION_SUCCESS = "authentication_success"
    AUTHENTICATION_FAILURE = "authentication_failure"
    USER_REGISTRATION = "user_registration"
    USER_REGISTRATION_FAILED = "user_registration_failed"
    DATA_ACCESS = "data_access"
    SUSPICIOUS_ACTIVITY = "suspicious_activity"
    INJECTION_ATTEMPT = "injection_attempt"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    SYSTEM_ERROR = "system_error"
    AUTH_LOGIN_SUCCESS = "auth_login_success"
    AUTH_LOGIN_FAILURE = "auth_login_failure"
    VIOLATION_RATE_LIMIT = "violation_rate_limit"
    AUTHZ_PERMISSION_DENIED = "authz_permission_denied"
    VIOLATION_SQL_INJECTION = "violation_sql_injection"
    DATA_PII_ACCESS = "data_pii_access"
    ACCOUNT_DELETED = "account_deleted"
    INPUT_VALIDATION_FAILED = "input_validation_failed"
    PII_DETECTED = "pii_detected"
    OUTPUT_BLOCKED = "output_blocked"
    DANGEROUS_OUTPUT_DETECTED = "dangerous_output_detected"
    BRUTE_FORCE_ATTEMPT = "brute_force_attempt"
    SUSPICIOUS_TOKEN = "suspicious_token"
    TOKEN_CREATED = "token_created"
    TOKEN_BLACKLISTED = "token_blacklist"
    TOKEN_REVOKED = "token_revoked"
