#!/usr/bin/env python3
"""
AUTO-GENERATED SECURE RANDOM REPLACEMENT SCRIPT
This script was generated by fix_insecure_random.py

RUN THIS SCRIPT TO APPLY SECURITY FIXES
"""

import re
from pathlib import Path

# Mapping of insecure patterns to secure replacements
REPLACEMENTS = [
    # Token generation
    (
        r"random\.randint\((\d+),\s*(\d+)\).*?(?:token|key)",
        lambda m: f"secrets.token_{16 if 'token' in m.group(0) else 'bytes'}(32)",
    ),
    # Password/security related
    (r"random\.choice\([^)]+\).*?(?:password|secret|key)", "secrets.token_urlsafe(32)"),
    # Generic high-security needs
    (r"random\.random\(\)", "secrets.SystemRandom().random()"),
    (r"random\.randint\((\d+),\s*(\d+)\)", r"secrets.randbelow( - ) + "),
    (r"random\.choice\(([^)]+)\)", r"secrets.choice()"),
]


def apply_fixes(file_path: Path):
    """Apply fixes to a single file"""
    try:
        content = file_path.read_text()
        original_content = content

        for pattern, replacement in REPLACEMENTS:
            if callable(replacement):
                content = re.sub(pattern, replacement, content, flags=re.IGNORECASE)
            else:
                content = re.sub(pattern, replacement, content, flags=re.IGNORECASE)

        if content != original_content:
            # Backup original
            backup_path = file_path.with_suffix(file_path.suffix + ".backup")
            backup_path.write_text(original_content)

            # Write fixed content
            file_path.write_text(content)
            print(f"✅ Fixed: {file_path}")

    except Exception as e:
        print(f"❌ Error fixing {file_path}: {e}")


if __name__ == "__main__":
    project_root = Path(__file__).parent

    print("🔧 Applying secure random fixes...")
    print("⚠️  Backups will be created as .backup files")
    print()

    # Apply fixes to all Python files (excluding tests)
    for py_file in project_root.rglob("*.py"):
        if "test" not in str(py_file) and "venv" not in str(py_file):
            apply_fixes(py_file)

    print()
    print("✨ Fixes applied! Review changes and remove .backup files when satisfied.")
