#!/bin/bash

# Manual Test Runner
# This script opens the browser and guides you through testing

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║          🧪 Race Condition Testing - Step by Step               ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Opening browser to http://localhost:5177/"
echo ""

# Open browser (works on macOS)
if [[ "$OSTYPE" == "darwin"* ]]; then
  open http://localhost:5177/
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  xdg-open http://localhost:5177/ 2>/dev/null || firefox http://localhost:5177/
else
  start http://localhost:5177/ 2>/dev/null
fi

echo "✅ Browser opened!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 TEST CHECKLIST (Follow these steps):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "【Step 1】Open DevTools Console"
echo "  • Press F12 (or right-click → Inspect)"
echo "  • Click the 'Console' tab"
echo "  • Keep console visible during testing"
echo ""
echo "【Step 2】Test 1 - Authentication Flow"
echo "  1. Log in with your credentials"
echo "  2. IMMEDIATELY click 'Back' button (before auth completes)"
echo "  3. Check console for warnings"
echo "  ✅ Expected: NO 'setState on unmounted' warnings"
echo ""
echo "【Step 3】Test 2 - Crisis Support"
echo "  1. Navigate to Crisis Support page"
echo "  2. IMMEDIATELY click 'Back' (before safety plan loads)"
echo "  3. Check console"
echo "  ✅ Expected: NO warnings or errors"
echo ""
echo "【Step 4】Test 3 - Emergency Call"
echo "  1. Navigate to Crisis Support page"
echo "  2. Click emergency call button (911 or 988)"
echo "  3. IMMEDIATELY navigate away (before 2-second timeout)"
echo "  4. Return and click emergency call again"
echo "  ✅ Expected: Only ONE timeout active, no multiple alerts"
echo ""
echo "【Step 5】Test 4 - Dashboard"
echo "  1. Navigate to Clinician Dashboard"
echo "  2. IMMEDIATELY navigate away (before data loads)"
echo "  3. Return to dashboard"
echo "  4. Wait 30 seconds for auto-refresh"
echo "  ✅ Expected: Auto-refresh works, no console warnings"
echo ""
echo "【Step 6】Test 5 - Session Expiry"
echo "  1. Let session expire (or trigger manually)"
echo "  2. Watch countdown timer"
echo "  3. Navigate away and back"
echo "  ✅ Expected: Countdown continues smoothly, no skips"
echo ""
echo "【Step 7】Test 6 - Team Updates"
echo "  1. Navigate to Teams page"
echo "  2. Select a team"
echo "  3. Rapidly update team name multiple times"
echo "  ✅ Expected: Updates show immediately, fresh data"
echo ""
echo "【Step 8】Test 7 - Team Deletion"
echo "  1. Select a team as current"
echo "  2. Delete that same team"
echo "  ✅ Expected: currentTeam set to null, no stale data"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ ALL TESTS PASS? (No console warnings)"
echo "   → Race conditions are FIXED!"
echo ""
echo "❌ SEE WARNINGS?"
echo "   → Check TESTING_GUIDE.md for troubleshooting"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Full test details: frontend/TESTING_GUIDE.md"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
