#!/usr/bin/env python3
"""
Simple Load Testing Script for PsychSync API
No external dependencies required - uses built-in libraries only
"""

import asyncio
import json
import random
import string
import time
import urllib.request
import urllib.error
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
import statistics

class SimpleLoadTester:
    """Simple load tester using urllib for maximum compatibility"""

    def __init__(self, base_url: str = "http://localhost:8000"):
        self.base_url = base_url
        self.results = []
        self.auth_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test"  # Default test token

    def make_request(self, endpoint: str, method: str = "GET",
                    payload: dict = None, headers: dict = None) -> dict:
        """Make a single HTTP request and return metrics"""
        start_time = time.time()
        url = f"{self.base_url}{endpoint}"

        try:
            # Prepare headers
            req_headers = {
                'User-Agent': 'SimpleLoadTester/1.0',
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            }
            if headers:
                req_headers.update(headers)
            if self.auth_token:
                req_headers['Authorization'] = f'Bearer {self.auth_token}'

            # Prepare request data
            data = None
            if payload and method in ['POST', 'PUT']:
                data = json.dumps(payload).encode('utf-8')

            # Create request
            req = urllib.request.Request(url, data=data, headers=req_headers, method=method)

            # Make request
            with urllib.request.urlopen(req, timeout=10) as response:
                response_data = response.read().decode('utf-8')
                response_time = (time.time() - start_time) * 1000

                return {
                    'status_code': response.getcode(),
                    'response_time_ms': response_time,
                    'response_size': len(response_data),
                    'success': True,
                    'error': None
                }

        except urllib.error.HTTPError as e:
            response_time = (time.time() - start_time) * 1000
            try:
                error_data = e.read().decode('utf-8')
                response_size = len(error_data)
            except (ValueError, TypeError, json.JSONDecodeError) as e:
                error_data = ""
                response_size = 0

            return {
                'status_code': e.code,
                'response_time_ms': response_time,
                'response_size': response_size,
                'success': e.code < 500,  # 4xx errors are "successful" error handling
                'error': str(e)
            }

        except Exception as e:
            response_time = (time.time() - start_time) * 1000
            return {
                'status_code': 0,
                'response_time_ms': response_time,
                'response_size': 0,
                'success': False,
                'error': str(e)
            }

    def run_user_simulation(self, user_id: int, duration_seconds: int = 60) -> list:
        """Simulate a single user for specified duration"""
        user_results = []
        end_time = time.time() + duration_seconds

        # Test endpoints with realistic weights
        endpoints = [
            ("/api/v1/health", "GET", None, 20),  # 20% health checks
            ("/api/v1/assessments", "GET", None, 25),  # 25% get assessments
            ("/api/v1/teams", "GET", None, 20),  # 20% get teams
            ("/api/v1/users/me", "GET", None, 15),  # 15% get profile
            ("/api/v1/analytics", "GET", None, 10),  # 10% get analytics
            ("/api/v1/assessments", "POST", {  # 10% create assessment
                "title": f"Test Assessment {user_id}",
                "description": f"Generated by user {user_id}"
            }, 10)
        ]

        # Expand weighted endpoints
        weighted_endpoints = []
        for endpoint, method, payload, weight in endpoints:
            weighted_endpoints.extend([(endpoint, method, payload)] * weight)

        while time.time() < end_time:
            # Random delay between requests
            time.sleep(random.uniform(0.5, 3.0))

            # Select random endpoint
            endpoint, method, payload = random.choice(weighted_endpoints)

            # Make request
            result = self.make_request(endpoint, method, payload)
            result['user_id'] = user_id
            result['endpoint'] = endpoint
            result['method'] = method
            result['timestamp'] = datetime.utcnow().isoformat()

            user_results.append(result)

        return user_results

    def run_load_test(self, num_users: int = 1000, test_duration: int = 60) -> dict:
        """Run load test with specified number of users"""
        print(f"🚀 Starting load test: {num_users} users for {test_duration} seconds")
        print(f"Target API: {self.base_url}")
        print("-" * 50)

        start_time = time.time()

        # Run simulations in parallel
        with ThreadPoolExecutor(max_workers=min(num_users, 100)) as executor:
            # Submit all user simulations
            futures = [
                executor.submit(self.run_user_simulation, user_id, test_duration)
                for user_id in range(num_users)
            ]

            # Collect results
            all_results = []
            completed = 0
            for future in as_completed(futures):
                try:
                    user_results = future.result(timeout=test_duration + 30)
                    all_results.extend(user_results)
                    completed += 1
                    if completed % 100 == 0:
                        print(f"Progress: {completed}/{num_users} users completed")
                except Exception as e:
                    print(f"User simulation failed: {e}")

        total_time = time.time() - start_time

        # Calculate metrics
        if all_results:
            response_times = [r['response_time_ms'] for r in all_results]
            successful = [r for r in all_results if r['success']]
            failed = [r for r in all_results if not r['success']]

            metrics = {
                'total_requests': len(all_results),
                'successful_requests': len(successful),
                'failed_requests': len(failed),
                'success_rate': (len(successful) / len(all_results)) * 100,
                'requests_per_second': len(all_results) / total_time,
                'avg_response_time_ms': statistics.mean(response_times),
                'median_response_time_ms': statistics.median(response_times),
                'min_response_time_ms': min(response_times),
                'max_response_time_ms': max(response_times),
                'p95_response_time_ms': sorted(response_times)[int(len(response_times) * 0.95)],
                'p99_response_time_ms': sorted(response_times)[int(len(response_times) * 0.99)],
                'total_data_transferred_mb': sum([r['response_size'] for r in all_results]) / (1024 * 1024),
                'test_duration_seconds': total_time,
                'concurrent_users': num_users
            }

            # Status code distribution
            status_codes = {}
            for result in all_results:
                status = result['status_code']
                status_codes[status] = status_codes.get(status, 0) + 1

            metrics['status_code_distribution'] = status_codes

        else:
            metrics = {
                'total_requests': 0,
                'successful_requests': 0,
                'failed_requests': 0,
                'success_rate': 0,
                'requests_per_second': 0,
                'avg_response_time_ms': 0,
                'median_response_time_ms': 0,
                'min_response_time_ms': 0,
                'max_response_time_ms': 0,
                'p95_response_time_ms': 0,
                'p99_response_time_ms': 0,
                'total_data_transferred_mb': 0,
                'test_duration_seconds': total_time,
                'concurrent_users': num_users,
                'status_code_distribution': {}
            }

        return metrics

    def test_error_handling(self):
        """Test various error scenarios"""
        print("🔍 Testing error handling scenarios...")
        print("-" * 30)

        error_tests = [
            ("Invalid endpoint", "/api/v1/nonexistent", "GET"),
            ("Wrong method", "/api/v1/health", "POST"),
            ("Missing auth", "/api/v1/users/me", "GET", {"remove_auth": True}),
            ("Invalid payload", "/api/v1/auth/login", "POST", {"invalid": "data"}),
            ("Non-existent user", "/api/v1/users/999999", "GET"),
            ("Very long endpoint", "/api/v1/" + "a" * 1000, "GET")
        ]

        results = []
        for test_name, endpoint, method, *extra in error_tests:
            headers = None
            payload = None

            if extra and isinstance(extra[0], dict) and "remove_auth" in extra[0]:
                headers = {}  # Remove auth
            elif extra and isinstance(extra[0], dict):
                payload = extra[0]

            result = self.make_request(endpoint, method, payload, headers)
            result['test_name'] = test_name
            results.append(result)

            # Check if error was handled gracefully
            graceful = result['success'] or (200 <= result['status_code'] < 600)
            status = "✅" if graceful else "❌"
            print(f"{status} {test_name}: HTTP {result['status_code']} ({result['response_time_ms']:.0f}ms)")

        return results

def main():
    """Main execution function"""
    print("🧪 Simple Load Testing Suite for PsychSync API")
    print("=" * 60)

    # Test error handling first
    tester = SimpleLoadTester("http://localhost:8000")

    try:
        # Quick connectivity test
        connectivity = tester.make_request("/api/v1/health")
        if connectivity['status_code'] not in [200, 401]:
            print("❌ Cannot connect to API server")
            return
        else:
            print("✅ API server is reachable")

        # Test error handling
        error_results = tester.test_error_handling()

        # Ask user for load test parameters
        print("\n⚙️  Load Test Configuration:")
        try:
            num_users = int(input("Number of concurrent users (default 1000): ") or "1000")
            duration = int(input("Test duration in seconds (default 60): ") or "60")
        except ValueError:
            print("Using defaults: 1000 users, 60 seconds")
            num_users = 1000
            duration = 60

        # Run load test
        print(f"\n🚀 Starting load test: {num_users:,} users for {duration} seconds")
        print("This may take a while...")

        metrics = tester.run_load_test(num_users, duration)

        # Display results
        print("\n📊 LOAD TEST RESULTS")
        print("=" * 60)
        print(f"📈 PERFORMANCE:")
        print(f"   • Total Requests: {metrics['total_requests']:,}")
        print(f"   • Successful: {metrics['successful_requests']:,} ({metrics['success_rate']:.1f}%)")
        print(f"   • Failed: {metrics['failed_requests']:,}")
        print(f"   • Requests/Second: {metrics['requests_per_second']:.1f}")
        print(f"   • Data Transferred: {metrics['total_data_transferred_mb']:.1f} MB")

        print(f"\n⚡ RESPONSE TIMES:")
        print(f"   • Average: {metrics['avg_response_time_ms']:.0f}ms")
        print(f"   • Median: {metrics['median_response_time_ms']:.0f}ms")
        print(f"   • P95: {metrics['p95_response_time_ms']:.0f}ms")
        print(f"   • P99: {metrics['p99_response_time_ms']:.0f}ms")
        print(f"   • Min: {metrics['min_response_time_ms']:.0f}ms")
        print(f"   • Max: {metrics['max_response_time_ms']:.0f}ms")

        print(f"\n🔢 STATUS CODE DISTRIBUTION:")
        for status, count in sorted(metrics['status_code_distribution'].items()):
            percentage = (count / metrics['total_requests']) * 100
            status_text = "✅ Success" if 200 <= status < 300 else "⚠️ Client Error" if 400 <= status < 500 else "❌ Server Error"
            print(f"   • HTTP {status}: {count:,} ({percentage:.1f}%) - {status_text}")

        # Performance assessment
        print(f"\n💡 PERFORMANCE ASSESSMENT:")
        recommendations = []

        if metrics['success_rate'] < 95:
            recommendations.append("❌ Low success rate - investigate error handling")

        if metrics['avg_response_time_ms'] > 2000:
            recommendations.append("⚠️  High average response time - optimize performance")

        if metrics['p95_response_time_ms'] > 5000:
            recommendations.append("🚨 Very high P95 response time - performance bottleneck")

        if metrics['requests_per_second'] < 100 and num_users > 500:
            recommendations.append("📈 Low RPS for user count - check system capacity")

        if not recommendations:
            recommendations.append("✅ Excellent performance under load!")

        for i, rec in enumerate(recommendations, 1):
            print(f"   {i}. {rec}")

        # Save results
        report_file = f"load_test_results_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.json"
        with open(report_file, 'w') as f:
            json.dump(metrics, f, indent=2, default=str)

        print(f"\n📄 Results saved to: {report_file}")

    except KeyboardInterrupt:
        print("\n⏹️  Load test cancelled by user")
    except Exception as e:
        print(f"\n❌ Load test failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
