"""Add missing User model columns

Revision ID: 003_add_user_columns
Revises: 002_anonymous_feedback_tables
Create Date: 2025-11-15 13:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003_add_user_columns'
down_revision: Union[str, None] = '002_anonymous_feedback_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add missing columns to users table based on User model
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True, server_default='UTC'))
    op.add_column('users', sa.Column('locale', sa.String(length=10), nullable=True, server_default='en-US'))
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # Authentication and verification fields
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))

    # Email verification fields
    op.add_column('users', sa.Column('email_verification_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True))

    # Password reset fields
    op.add_column('users', sa.Column('password_reset_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove the columns we added
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'email_verification_expires')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'timezone')

    # ### end Alembic commands ###