"""Add user role field

Revision ID: 007b_add_user_role_field
Revises: 006_add_data_anonymization_tables
Create Date: 2025-11-19 11:20:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "007b_add_user_role_field"
down_revision: Union[str, None] = "007_add_performance_indexes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create UserRole enum type
    user_role_enum = postgresql.ENUM("admin", "user", "team_lead", name="userrole")
    user_role_enum.create(op.get_bind())

    # Add role column to users table
    op.add_column(
        "users",
        sa.Column("role", user_role_enum, nullable=False, server_default="user"),
    )

    # Create index on role for performance
    op.create_index("idx_users_role", "users", ["role"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the index
    op.drop_index("idx_users_role", table_name="users")

    # Drop the role column
    op.drop_column("users", "role")

    # Drop the enum type
    user_role_enum = postgresql.ENUM("admin", "user", "team_lead", name="userrole")
    user_role_enum.drop(op.get_bind())

    # ### end Alembic commands ###
