"""create onboarding tables

Revision ID: 008
Revises:
- Create tables for onboarding analytics
- Add A/B testing support
- Add user journey tracking

Create Date: 2024-01-28 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '008'
down_revision = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create onboarding_analytics table
    op.create_table('onboarding_analytics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=True),
        sa.Column('session_id', sa.String(length=255), nullable=True),
        sa.Column('test_name', sa.String(length=100), nullable=True),
        sa.Column('variant', sa.String(length=50), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('pk_onboarding_analytics')
    )
    op.create_index('ix_onboarding_analytics_user_id', 'onboarding_analytics', ['user_id'], unique=False)
    op.create_index('ix_onboarding_analytics_session_id', 'onboarding_analytics', ['session_id'], unique=False)
    op.create_index('ix_onboarding_analytics_timestamp', 'onboarding_analytics', ['timestamp'], unique=False)
    op.create_index('ix_onboarding_analytics_event_type', 'onboarding_analytics', ['event_type'], unique=False)

    # Create ab_test_assignments table
    op.create_table('ab_test_assignments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('test_name', sa.String(length=100), nullable=False),
        sa.Column('user_identifier', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=True),
        sa.Column('session_id', sa.String(length=255), nullable=True),
        sa.Column('variant', sa.String(length=50), nullable=False),
        sa.Column('variant_name', sa.String(length=200), nullable=False),
        sa.Column('features', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('segments', sa.JSON(), nullable=True),
        sa.Column('assigned_at', sa.DateTime(), nullable=False),
        sa.Column('assignment_method', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('pk_ab_test_assignments')
    )
    op.create_index('ix_ab_test_assignments_user_id', 'ab_test_assignments', ['user_id'], unique=False)
    op.create_index('ab_test_assignments_session_id', 'ab_test_assignments', ['session_id'], unique=False)
    op.create_index('ab_test_assignments_test_name', 'ab_test_assignments', ['test_name'], unique=False)
    op.create_index('ab_test_assignments_variant', 'ab_test_assignments', ['variant'], unique=False)
    op.create_index('ab_test_assignments_assigned_at', 'ab_test_assignments', ['assigned_at'], unique=False)

    # Create user_onboarding_status table
    op.create_table('user_onboarding_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('is_authenticated', sa.Boolean(), nullable=False),
        sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
        sa.Column('current_step', sa.String(length=100), nullable=True),
        sa.Column('completed_steps', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('recommended_actions', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('progress_percentage', sa.Float(), nullable=False),
        sa.Column('estimated_remaining_time', sa.String(length=50), nullable=True),
        sa.Column('last_activity', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('pk_user_onboarding_status'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.UniqueConstraint('uq_user_onboarding_status_user_id')
    )
    op.create_index('ix_user_onboarding_status_user_id', 'user_onboarding_status', ['user_id'], unique=True)
    op.create_index('ix_user_onboarding_status_progress', 'user_onboarding_status', ['progress_percentage'], unique=False)

    # Create hris_integrations table
    op.create_table('hris_integrations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('hris_type', sa.String(length=50), nullable=False),
        sa.Column('hris_name', sa.String(length=200), nullable=True),
        sa.Column('config', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='inactive'),
        sa.Column('connected_at', sa.DateTime(), nullable=True),
        sa.Column('last_sync', sa.DateTime(), nullable=True),
        sa.Column('sync_frequency', sa.String(length=50), nullable=True),
        sa.Column('webhook_url', sa.String(length=500), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('pk_hris_integrations'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_index('ix_hris_integrations_user_id', 'hris_integrations', ['user_id'], unique=False)
    op.create_index('ix_hris_integrations_hris_type', 'hris_integrations', ['hris_type'], unique=False)
    op.create_index('ix_hris_integrations_status', 'hris_integrations', ['status'], unique=False)

    # Create hris_sync_logs table
    op.create_table('hris_sync_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hris_integration_id', sa.Integer(), nullable=False),
        sa.Column('sync_type', sa.String(length=50), nullable=False),
        sa.Column('records_count', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('pk_hris_sync_logs'),
        sa.ForeignKeyConstraint(['hris_integration_id'], ['hris_integrations.id'], )
    )
    op.create_index('ix_hris_sync_logs_hris_integration_id', 'hris_sync_logs', ['hris_integration_id'], unique=False)
    extant

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hris_sync_logs')
    op.drop_index('ix_hris_sync_logs_hris_integration_id', table='hris_sync_logs')
    op.drop_table('hris_integrations')
    op.drop_index('ix_hris_integrations_status', table='hris_integrations')
    op.drop_index('ix_hris_integrations_hris_type', table='hris_integrations')
    op.drop_index('ix_hris_integrations_user_id', table='hris_integrations')
    op.drop_constraint('fk_hris_integrations_user_id')
    op.drop_table('user_onboarding_status')
    op.drop_constraint('uq_user_onboarding_status_user_id')
    op.drop_index('ix_user_onboarding_status_progress', table='user_onboarding_status')
    op.drop_index('ix_user_onboarding_status_user_id', table='user_onboarding_status')
    op.drop_constraint('fk_user_onboarding_status_user_id')
    op.drop_table('ab_test_assignments')
    op.drop_index('ix_ab_test_assignments_assigned_at', table='ab_test_assignments')
    op.drop_index('ix_ab_test_assignments_variant', table='ab_test_assignments')
    op.drop_index('ix_ab_test_assignments_test_name', table='ab_test_assignments')
    op.drop_index('ab_test_assignments_session_id', table='ab_test_assignments')
    op.drop_index('ab_test_assignments_user_id', table='ab_test_assignments')
    op.drop_table('onboarding_analytics')
    op.drop_index('ix_onboarding_analytics_event_type', table='onboarding_analytics')
    op.drop_index('ix_onboarding_analytics_timestamp', table='onboarding_analytics')
    op.drop_index('ix_onboarding_analytics_session_id', table='onboarding_analytics')
    op.drop_index('ix_onboarding_analytics_user_id', table='onboarding_analytics')
    # ### end Alembic commands ###
