"""create hris integration tables

Revision ID: 009
Revises:
- Create HRIS employee and data tables
- Add foreign key constraints
- Add indexes for performance

Create Date: 2024-01-28 14:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '009'
down_revision = '008'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create hris_employees table
    op.create_table('hris_employees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hris_integration_id', sa.Integer(), nullable=False),
        sa.Column('hris_employee_id', sa.String(length=100), nullable=False),
        sa.Column('psychsync_user_id', sa.String(length=36), nullable=True),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('department', sa.String(length=100), nullable=True),
        sa.Column('position', sa.String(length=100), nullable=True),
        sa.Column('employment_status', sa.String(length=20), nullable=False),
        sa.Column('manager_id', sa.String(length=100), nullable=True),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('hire_date', sa.Date(), nullable=True),
        sa.Column('termination_date', sa.Date(), nullable=True),
        sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('data_sync_date', sa.DateTime(), nullable=True),
        sa.Column('data_source', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('pk_hris_employees'),
        sa.ForeignKeyConstraint(['hris_integration_id'], ['hris_integrations.id'], ),
        sa.ForeignKeyConstraint(['psychsync_user_id'], ['users.id'], )
    )
    op.create_index('ix_hris_employees_hris_integration_id', 'hris_employees', ['hris_integration_id'], unique=False)
    op.create_index('ix_hris_employees_psychsync_user_id', 'hris_employees', ['psychsync_user_id'], unique=False)
    op.create_index('ix_hris_employees_email', 'hris_employees', ['email'], unique=False)
    op.create_index('ix_hris_employees_department', 'hris_employees', ['department'], unique=False)
    op.create_index('ix_hris_employees_employment_status', 'hris_employees', ['employment_status'], unique=False)
    op.create_index('ix_hris_employees_hris_employee_id', 'hris_employees', ['hris_employee_id'], unique=False)
    op.create_index('ix_hris_employees_data_sync_date', 'hris_employees', ['data_sync_date'], unique=False)

    # Create hris_attendance table
    op.create_table('hris_attendance',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hris_integration_id', sa.Integer(), nullable=False),
        sa.Column('hris_employee_id', sa.String(length=100), nullable=False),
        sa.Column('attendance_date', sa.Date(), nullable=False),
        sa.Column('clock_in', sa.DateTime(), nullable=True),
        sa.Column('clock_out', sa.DateTime(), nullable=True),
        sa.Column('break_duration', sa.Integer(), nullable=True),
        sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='present'),
        sa.Column('shift_type', sa.String(length=50), nullable=True),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('pk_hris_attendance'),
        sa.ForeignKeyConstraint(['hris_integration_id'], ['hris_integrations.id'], )
    )
    op.create_index('ix_hris_attendance_hris_integration_id', 'hris_attendance', ['hris_integration_id'], unique=False)
    op.create_index('ix_hris_attendance_hris_employee_id', 'hris_attendance', ['hris_employee_id'], unique=False)
    op.create_index('ix_hris_attendance_attendance_date', 'hris_attendance', ['attendance_date'], unique=False)
    op.create_index('ix_hris_attendance_status', 'hris_attendance', ['status'], unique=False)

    # Create hris_leave_records table
    op.create_table('hris_leave_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hris_integration_id', sa.Integer(), nullable=False),
        sa.Column('hris_employee_id', sa.String(length=100), nullable=False),
        sa.Column('leave_type', sa.String(length=50), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('days_taken', sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('approver_id', sa.String(length=100), nullable=True),
        sa.Column('approved_date', sa.Date(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('pk_hris_leave_records'),
        sa.ForeignKeyConstraint(['hris_integration_id'], ['hris_integrations.id'], )
    )
    op.create_index('ix_hris_leave_records_hris_integration_id', 'hris_leave_records', ['hris_integration_id'], unique=False)
    op.create_index('ix_hris_leave_records_hris_employee_id', 'hris_leave_records', ['hris_employee_id'], unique=False)
    op.create_index('ix_hris_leave_records_leave_type', 'hris_leave_records', ['leave_type'], unique=False)
    op.create_index('ix_hris_leave_records_status', 'hris_leave_records', ['status'], unique=False)
    op.create_index('ix_hris_leave_records_start_date', 'hris_leave_records', ['start_date'], unique=False)

    # Create hris_performance_reviews table
    op.create_table('hris_performance_reviews',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hris_integration_id', sa.Integer(), nullable=False),
        sa.Column('hris_employee_id', sa.String(length=100), nullable=False),
        sa.Column('reviewer_id', sa.String(length=100), nullable=True),
        sa.Column('review_date', sa.Date(), nullable=False),
        sa.Column('review_period', sa.String(length=50), nullable=True),
        sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column('max_rating', sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.Column('goals', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('competencies', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='completed'),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('pk_hris_performance_reviews'),
        sa.ForeignKeyConstraint(['hris_integration_id'], ['hris_integrations.id'], )
    )
    op.create_index('ix_hris_performance_reviews_hris_integration_id', 'hris_performance_reviews', ['hris_integration_id'], unique=False)
    op.create_index('ix_hris_performance_reviews_hris_employee_id', 'hris_performance_reviews', ['hris_employee_id'], unique=False)
    op.create_index('ix_hris_performance_reviews_reviewer_id', 'hris_performance_reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_hris_performance_reviews_review_date', 'hris_performance_reviews', ['review_date'], unique=False)
    op.create_index('ix_hris_performance_reviews_rating', 'hris_performance_reviews', ['rating'], unique=False)
    op.create_index('ix_hris_performance_reviews_status', 'hris_performance_reviews', ['status'], unique=False)

    # Add description column to existing tables for PostgreSQL
    with op.batch_alter_table('hris_integrations') as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('onboarding_preferences', sa.JSON(), nullable=True))

    with op.batch_alter_table('teams') as batch_op:
        batch_op.add_column(sa.Column('hris_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_hris_sync', sa.DateTime(), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove columns from existing tables
    with op.batch_alter_table('teams') as batch_op:
        batch_op.drop_column('last_hris_sync')
        batch_op.drop_column('hris_data')

    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('onboarding_preferences')

    with op.batch_alter_table('hris_integrations') as batch_op:
        batch_op.drop_column('description')

    # Drop indexes and constraints
    op.drop_index('ix_hris_performance_reviews_status', table='hris_performance_reviews')
    op.drop_index('ix_hris_performance_reviews_rating', table='hris_performance_reviews')
    op.drop_index('ix_hris_performance_reviews_review_date', table='hris_performance_reviews')
    op.drop_index('ix_hris_performance_reviews_reviewer_id', table='hris_performance_reviews')
    op.drop_index('ix_hris_performance_reviews_hris_employee_id', table='hris_performance_reviews')
    op.drop_index('ix_hris_performance_reviews_hris_integration_id', table='hris_performance_reviews')
    op.drop_table('hris_performance_reviews')
    op.drop_constraint('fk_hris_performance_reviews_hris_integration_id')

    op.drop_index('ix_hris_leave_records_status', table='hris_leave_records')
    op.drop_index('ix_hris_leave_records_start_date', table='hris_leave_records')
    op.drop_index('ix_hris_leave_records_leave_type', table='hris_leave_records')
    op.drop_index('ix_hris_leave_records_hris_employee_id', table='hris_leave_records')
    op.drop_index('ix_hris_leave_records_hris_integration_id', table='hris_leave_records')
    op.drop_table('hris_leave_records')
    op.drop_constraint('fk_hris_leave_records_hris_integration_id')

    op.drop_index('ix_hris_attendance_status', table='hris_attendance')
    op.drop_index('ix_hris_attendance_attendance_date', table='hris_attendance')
    op.drop_index('ix_hris_attendance_hris_employee_id', table='hris_attendance')
    op.drop_index('ix_hris_attendance_hris_integration_id', table='hris_attendance')
    op.drop_table('hris_attendance')
    op.drop_constraint('fk_hris_attendance_hris_integration_id')

    op.drop_index('ix_hris_employees_data_sync_date', table='hris_employees')
    op.drop_index('ix_hris_employees_hris_employee_id', table='hris_employees')
    op.drop_index('ix_hris_employees_employment_status', table='hris_employees')
    op.drop_index('ix_hris_employees_department', table='hris_employees')
    op.drop_index('ix_hris_employees_email', table='hris_employees')
    op.drop_index('ix_hris_employees_psychsync_user_id', table='hris_employees')
    op.drop_index('ix_hris_employees_hris_integration_id', table='hris_employees')
    op.drop_constraint('fk_hris_employees_psychsync_user_id')
    op.drop_constraint('fk_hris_employees_hris_integration_id')
    op.drop_table('hris_employees')
