"""Add critical database indexes for performance

Revision ID: 009_add_critical_database_indexes
Revises: 008_create_assessment_tables
Create Date: 2025-11-19 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009_add_critical_database_indexes'
down_revision: Union[str, None] = '008_create_assessment_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add critical composite indexes for user table
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_org_active', 'users', ['organization_id', 'is_active'], unique=False)
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_last_login', 'users', ['last_login'], unique=False)

    # Add indexes for team table
    op.create_index('idx_team_org_created', 'teams', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_team_creator', 'teams', ['created_by_id', 'created_at'], unique=False)
    op.create_index('idx_team_name_search', 'teams', ['name'], unique=False)

    # Add indexes for team members table
    op.create_index('idx_team_members_team_role', 'team_members', ['team_id', 'role'], unique=False)
    op.create_index('idx_team_members_user_active', 'team_members', ['user_id'], unique=False)
    op.create_index('idx_team_members_lookup', 'team_members', ['team_id', 'user_id', 'role'], unique=False)

    # Add indexes for assessment tables
    op.create_index('idx_assessment_creator', 'assessments', ['created_by_id', 'created_at'], unique=False)
    op.create_index('idx_assessment_org_status', 'assessments', ['organization_id', 'status'], unique=False)
    op.index('idx_assessment_framework', 'assessments', ['framework_code'], unique=False)
    op.index('idx_assessment_created_at', 'assessments', ['created_at'], unique=False)

    # Add indexes for assessment sections
    op.create_index('idx_assessment_sections_assessment', 'assessment_sections', ['assessment_id'], unique=False)
    op.create_index('idx_assessment_sections_order', 'assessment_sections', ['assessment_id', 'order'], unique=False)

    # Add indexes for questions
    op.create_index('idx_questions_section', 'questions', ['section_id'], unique=False)
    op.create_index('idx_questions_order', 'questions', ['section_id', 'order'], unique=False)

    # Add indexes for responses
    op.create_index('idx_responses_assessment_user', 'responses', ['assessment_id', 'user_id'], unique=False)
    op.create_index('idx_responses_user_created', 'responses', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_responses_assessment_created', 'responses', ['assessment_id', 'created_at'], unique=False)

    # Add indexes for assessment responses
    op.create_index('idx_assessment_responses_assessment', 'assessment_responses', ['assessment_id'], unique=False)
    op.create_index('idx_assessment_responses_respondent', 'assessment_responses', ['respondent_id'], unique=False)
    op.create_index('idx_assessment_responses_status', 'assessment_responses', ['status'], unique=False)

    # Add indexes for assessment assignments
    op.create_index('idx_assessment_assignments_assessment', 'assessment_assignments', ['assessment_id'], unique=False)
    op.create_index('idx_assessment_assignments_user', 'assessment_assignments', ['user_id'], unique=False)
    op.create_index('idx_assessment_assignments_completed', 'assessment_assignments', ['completed'], unique=False)

    # Add indexes for organizations
    op.create_index('idx_organization_created_at', 'organizations', ['created_at'], unique=False)
    op.index('idx_organization_name', 'organizations', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes from organizations
    op.drop_index('idx_organization_name', table_name='organizations')
    op.drop_index('idx_organization_created_at', table_name='organizations')

    # Drop indexes from assessment assignments
    op.drop_index('idx_assessment_assignments_completed', table_name='assessment_assignments')
    op.drop_index('idx_assessment_assignments_user', table_name='assessment_assignments')
    op.drop_index('idx_assessment_assignments_assessment', table_name='assessment_assignments')

    # Drop indexes from assessment responses
    op.drop_index('idx_assessment_responses_status', table_name='assessment_responses')
    op.drop_index('idx_assessment_responses_respondent', table_name='assessment_responses')
    op.drop_index('idx_assessment_responses_assessment', table_name='assessment_responses')

    # Drop indexes from responses
    op.drop_index('idx_responses_assessment_created', table_name='responses')
    op.drop_index('idx_responses_user_created', table_name='responses')
    op.drop_index('idx_responses_assessment_user', table_name='responses')

    # Drop indexes from questions
    op.drop_index('idx_questions_order', table_name='questions')
    op.drop_index('idx_questions_section', table_name='questions')

    # Drop indexes from assessment sections
    op.drop_index('idx_assessment_sections_order', table_name='assessment_sections')
    op.drop_index('idx_assessment_sections_assessment', table_name='assessment_sections')

    # Drop indexes from assessments
    op.drop_index('idx_assessment_created_at', table_name='assessments')
    op.index('idx_assessment_framework', table_name='assessments')
    op.drop_index('idx_assessment_org_status', table_name='assessments')
    op.drop_index('idx_assessment_creator', table_name='assessments')

    # Drop indexes from team members
    op.drop_index('idx_team_members_lookup', table_name='team_members')
    op.drop_index('idx_team_members_user_active', table_name='team_members')
    op.drop_index('idx_team_members_team_role', table_name='team_members')

    # Drop indexes from teams
    op.drop_index('idx_team_name_search', table_name='teams')
    op.drop_index('idx_team_creator', table_name='teams')
    op.drop_index('idx_team_org_created', table_name='teams')

    # Drop indexes from users
    op.drop_index('idx_user_last_login', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_index('idx_user_org_active', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')

    # ### end Alembic commands ###
