"""Add user role field to users table - CRITICAL FIX

Revision ID: 013_add_user_role_to_base
Revises: 003_add_user_columns
Create Date: 2025-11-22 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '013_add_user_role_to_base'
down_revision: Union[str, None] = '003_add_user_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the enum type first
    op.execute("CREATE TYPE userrole AS ENUM ('ADMIN', 'USER', 'TEAM_LEAD')")

    # Add user_role field with default value
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', 'TEAM_LEAD', name='userrole'), nullable=False, server_default='USER'))

    # Create index for role field
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop index first
    op.drop_index(op.f('ix_users_role'), table_name='users')

    # Drop column
    op.drop_column('users', 'role')

    # Drop the enum type
    op.execute("DROP TYPE userrole")

    # ### end Alembic commands ###
