"""Add missing user fields

Revision ID: e54429b44d1d
Revises: 003_add_user_columns
Create Date: 2025-11-16 11:33:33.216860

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e54429b44d1d"
down_revision: Union[str, None] = "003_longitudinal_analysis"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anonymous_feedback_pattern")
    op.drop_table("organizations")
    op.drop_table("users")
    op.drop_index("ix_anonymous_feedback_tracking_id", table_name="anonymous_feedback")
    op.drop_table("anonymous_feedback")
    op.drop_table("anonymous_feedback_template")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymous_feedback_template",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "feedback_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "template_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "description_template", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "example_situations",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "guidance_questions",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "required_elements",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="anonymous_feedback_template_organization_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="anonymous_feedback_template_pkey"),
    )
    op.create_table(
        "anonymous_feedback",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "tracking_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "feedback_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "severity", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "target_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "target_id_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "evidence_urls",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "submitter_fingerprint",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "submitted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "resolution_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "assigned_reviewer_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column("reviewer_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "public_resolution_notes", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "urgency_score", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column(
            "auto_assigned", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column(
            "investigation_priority",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "incident_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "actions_taken_summary", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("internal_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_reviewer_id"],
            ["users.id"],
            name="anonymous_feedback_assigned_reviewer_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="anonymous_feedback_organization_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="anonymous_feedback_pkey"),
        sa.UniqueConstraint("tracking_id", name="anonymous_feedback_tracking_id_key"),
    )
    op.create_index(
        "ix_anonymous_feedback_tracking_id",
        "anonymous_feedback",
        ["tracking_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("email", postgresql.CITEXT(), autoincrement=False, nullable=False),
        sa.Column("password_hash", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("full_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("avatar_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "timezone",
            sa.VARCHAR(length=50),
            server_default=sa.text("'UTC'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "locale",
            sa.VARCHAR(length=10),
            server_default=sa.text("'en-US'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_verified",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_superuser",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_login",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "email_verification_token", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "email_verification_expires",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "password_reset_token", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "password_reset_expires",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], name="users_organization_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint("email", name="users_email_key"),
    )
    op.create_table(
        "organizations",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="organizations_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "anonymous_feedback_pattern",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "pattern_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "affected_categories",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "pattern_description", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "confidence_score",
            sa.VARCHAR(length=10),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sample_size", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "time_period_days",
            sa.VARCHAR(length=10),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "first_detected", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="anonymous_feedback_pattern_organization_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="anonymous_feedback_pattern_pkey"),
    )
    # ### end Alembic commands ###
