"""
Security Detection Rules

Real-time detection of:
- Abnormal agent/tool invocation patterns
- Indirect prompt injection markers
- Data exfiltration attempts
- Privilege escalation patterns
- Anomalous behavior

Implements MITRE ATT&CK technique detection.
"""

from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
import json
import re
from typing import Any

from app.security.logging.schemas import (
    DataAccessEvent,
    EventSeverity,
    EventType,
    SecurityEvent,
    ToolInvocationEvent,
)


class DetectionType(str, Enum):
    """Types of detection rules"""
    # Injection Detection
    PROMPT_INJECTION = "prompt_injection"
    INDIRECT_INJECTION = "indirect_injection"
    JAILBREAK_ATTEMPT = "jailbreak_attempt"
    DATA_EXFILTRATION = "data_exfiltration"

    # Anomaly Detection
    ABNORMAL_TOOL_CALL = "abnormal_tool_call"
    EXCESSIVE_TOOL_USE = "excessive_tool_use"
    FORBIDDEN_TOOL_COMBINATION = "forbidden_tool_combination"
    SUSPICIOUS_PARAMETER_PATTERN = "suspicious_parameter_pattern"

    # Access Pattern Detection
    BULK_DATA_ACCESS = "bulk_data_access"
    PRIVILEGE_ESCALATION = "privilege_escalation"
    IMPOSSIBLE_TRAVEL = "impossible_travel"
    UNUSUAL_TIME_ACCESS = "unusual_time_access"

    # Behavior Detection
    BRUTE_FORCE = "brute_force"
    CREDENTIAL_STUFFING = "credential_stuffing"
    ACCOUNT_TAKEOVER = "account_takeover"


@dataclass
class DetectionRule:
    """Definition of a detection rule"""
    rule_id: str
    name: str
    description: str
    detection_type: DetectionType
    severity: EventSeverity
    enabled: bool = True

    # Matching criteria
    event_types: list[EventType] = field(default_factory=list)
    patterns: list[str] = field(default_factory=list)
    threshold: int | None = None  # For count-based rules
    time_window_seconds: int | None = None  # For time-based rules

    # MITRE ATT&CK mapping
    mitre_tactics: list[str] = field(default_factory=list)
    mitre_techniques: list[str] = field(default_factory=list)

    # Metadata
    reference: str | None = None
    false_positive_rate: str = "low"  # low, medium, high


@dataclass
class DetectionAlert:
    """Alert generated by detection rule"""
    alert_id: str
    rule_id: str
    rule_name: str
    detection_type: DetectionType
    severity: EventSeverity
    timestamp: datetime

    # Matching events
    triggering_events: list[SecurityEvent]
    event_count: int

    # Detection details
    detection_details: dict[str, Any] = field(default_factory=dict)
    confidence_score: float = 0.0  # 0.0 to 1.0

    # Mitigation
    mitigation_suggestions: list[str] = field(default_factory=list)

    # Status
    acknowledged: bool = False
    investigated: bool = False
    false_positive: bool = False


class SecurityEventDetector:
    """
    Detects security threats using pattern matching and behavioral analysis.

    Maintains rolling windows of recent events for temporal analysis.
    """

    def __init__(self):
        self.rules: list[DetectionRule] = []
        self.alerts: list[DetectionAlert] = []
        self._event_history: list[tuple[datetime, SecurityEvent]] = []
        self._max_history_hours = 24

        # Initialize default rules
        self._initialize_default_rules()

    def _initialize_default_rules(self):
        """Initialize default detection rules"""
        rules = [
            # Injection Detection Rules
            DetectionRule(
                rule_id="injection-001",
                name="Direct Prompt Injection",
                description="Detects direct prompt injection attempts via text manipulation commands",
                detection_type=DetectionType.PROMPT_INJECTION,
                severity=EventSeverity.HIGH,
                event_types=[EventType.MODEL_PROMPT],
                patterns=[
                    r"ignore\s+(all\s+)?(previous|above)\s+instructions",
                    r"disregard\s+(everything|all\s+instructions)",
                    r"(forget|discard|clear)\s+(previous|all)\s+(instructions|prompts)",
                    r"new\s+(task|instructions|role):",
                    r"act\s+as\s+(if\s+you\s+are\s+not\s+an?\s+AI)?",
                    r"you\s+are\s+now\s+(a|an)",
                    r"override\s+(your\s+)?(programming|training|instructions)",
                    r"replace\s+(your\s+)?(persona|character)",
                ],
                mitre_tactics=["Initial Access", "Execution"],
                mitre_techniques=["T1190", "T1059"],
                reference="https://owasp.org/www-project-top-10-for-large-language-model-applications/"
            ),
            DetectionRule(
                rule_id="injection-002",
                name="Indirect Prompt Injection",
                description="Detects indirect injection via external data sources, file contents, or tool outputs",
                detection_type=DetectionType.INDIRECT_INJECTION,
                severity=EventSeverity.CRITICAL,
                event_types=[EventType.MODEL_PROMPT, EventType.TOOL_INVOCATION],
                patterns=[
                    r"(translate|interpret|process|execute)\s+the\s+(following|below)",
                    r"the\s+(file|document|text|content|data)\s+(says|states|contains)",
                    r"(according|based)\s+on\s+(the\s+)?(above|below)",
                    r"hidden\s+(instruction|command|prompt)",
                    r"system\s+(message|prompt|instruction)",
                    r"(developer|administrator|user)\s+message:",
                ],
                mitre_tactics=["Initial Access", "Execution"],
                mitre_techniques=["T1190", "T1059"],
                reference="https://arxiv.org/abs/2309.05467"
            ),
            DetectionRule(
                rule_id="injection-003",
                name="Jailbreak Attempt",
                description="Detects jailbreak attempts using role-playing, character adoption, or hypothetical scenarios",
                detection_type=DetectionType.JAILBREAK_ATTEMPT,
                severity=EventSeverity.HIGH,
                event_types=[EventType.MODEL_PROMPT],
                patterns=[
                    r"(let\s+s?imagine|imagine|hypothetically|pretend)",
                    r"(role.?play|act\s+as|assume\s+the\s+role)",
                    r"(you\s+are|you\'re)\s+(now\s+)?(a|an)\s+",
                    r"for\s+educational\s+purposes",
                    r"in\s+(a\s+)?(fictional|hypothetical|role-play)",
                    r"(developer\s+mode|sudo\s+mode|admin\s+mode)",
                    r"unrestricted\s+(mode|code|output)",
                    r"(no|disable|bypass)\s+(filter|restriction|constraint|censorship)",
                ],
                mitre_tactics=["Execution", "Bypass Security"],
                mitre_techniques=["T1059"],
                reference="https://llm-attacks.org/"
            ),

            # Abnormal Tool Call Rules
            DetectionRule(
                rule_id="tool-001",
                name="Suspicious Tool Parameter Pattern",
                description="Detects SQL injection, command injection, or path traversal in tool parameters",
                detection_type=DetectionType.SUSPICIOUS_PARAMETER_PATTERN,
                severity=EventSeverity.CRITICAL,
                event_types=[EventType.TOOL_INVOCATION],
                patterns=[
                    r"(\bor\s+1\s*=\s*1|'|\-\-|;|\||\|&&)",  # SQL injection
                    r"(;|\|&&|\|\|)`.*`",  # Command injection
                    r"\.\./|\.\.\\\\",  # Path traversal
                    r"<script|javascript:",  # XSS
                    r"(\${|#\{|\[.*\]\(.*\))",  # Template injection
                ],
                mitre_tactics=["Execution", "Initial Access"],
                mitre_techniques=["T1059", "T1190"]
            ),
            DetectionRule(
                rule_id="tool-002",
                name="Forbidden Tool Combination",
                description="Detects dangerous combinations of tools that may indicate attack chains",
                detection_type=DetectionType.FORBIDDEN_TOOL_COMBINATION,
                severity=EventSeverity.HIGH,
                event_types=[EventType.TOOL_INVOCATION],
                # This is handled in analyze_tool_combinations
                reference="Attack chain detection"
            ),
            DetectionRule(
                rule_id="tool-003",
                name="Excessive Tool Use",
                description="Detects unusually high frequency of tool calls (potential scraping or probing)",
                detection_type=DetectionType.EXCESSIVE_TOOL_USE,
                severity=EventSeverity.MEDIUM,
                event_types=[EventType.TOOL_INVOCATION],
                threshold=50,  # 50 tool calls
                time_window_seconds=60,  # within 60 seconds
                mitre_tactics=["Collection", "Discovery"],
                mitre_techniques=["T1005", "T1018"]
            ),

            # Data Exfiltration Rules
            DetectionRule(
                rule_id="data-001",
                name="Bulk Data Access",
                description="Detects access to unusually large amounts of data",
                detection_type=DetectionType.BULK_DATA_ACCESS,
                severity=EventSeverity.HIGH,
                event_types=[EventType.DATA_ACCESS_READ, EventType.DATA_EXPORT],
                threshold=1000,  # 1000 records
                time_window_seconds=300,  # within 5 minutes
                mitre_tactics=["Collection", "Exfiltration"],
                mitre_techniques=["T1005", "T1041"]
            ),
            DetectionRule(
                rule_id="data-002",
                name="Data Exfiltration Pattern",
                description="Detects potential data exfiltration via export or encoding",
                detection_type=DetectionType.DATA_EXFILTRATION,
                severity=EventSeverity.CRITICAL,
                event_types=[EventType.DATA_EXPORT, EventType.TOOL_INVOCATION],
                patterns=[
                    r"(base64|hex|encode|encrypt|compress)",
                    r"\.(zip|tar|gz|rar|7z)",
                    r"(pastebin|dropbox|google\s+drive|onedrive)",
                    r"(ftp|sftp|scp|rsync)",
                ],
                mitre_tactics=["Exfiltration"],
                mitre_techniques=["T1041", "T1567"]
            ),

            # Access Pattern Rules
            DetectionRule(
                rule_id="access-001",
                name="Impossible Travel",
                description="Detects logins from geographically impossible locations",
                detection_type=DetectionType.IMPOSSIBLE_TRAVEL,
                severity=EventSeverity.HIGH,
                event_types=[EventType.AUTH_LOGIN_SUCCESS],
                # This is handled in analyze_access_patterns
                mitre_tactics=["Initial Access", "Credential Access"],
                mitre_techniques=["T1078"]
            ),
            DetectionRule(
                rule_id="access-002",
                name="Unusual Time Access",
                description="Detects access outside normal business hours",
                detection_type=DetectionType.UNUSUAL_TIME_ACCESS,
                severity=EventSeverity.LOW,
                event_types=[EventType.AUTH_LOGIN_SUCCESS, EventType.DATA_ACCESS_READ],
                # This is handled in analyze_access_patterns
                reference="Behavioral analysis"
            ),

            # Privilege Escalation
            DetectionRule(
                rule_id="priv-001",
                name="Privilege Escalation",
                description="Detects rapid privilege escalation or unusual permission changes",
                detection_type=DetectionType.PRIVILEGE_ESCALATION,
                severity=EventSeverity.HIGH,
                event_types=[EventType.PRIV_ROLE_GRANTED, EventType.PRIV_PERMISSION_GRANTED],
                patterns=[],
                # This is handled in analyze_privilege_escalation
                mitre_tactics=["Privilege Escalation", "Persistence"],
                mitre_techniques=["T1484", "T1098"]
            ),

            # Brute Force
            DetectionRule(
                rule_id="auth-001",
                name="Brute Force Attack",
                description="Detects multiple failed login attempts",
                detection_type=DetectionType.BRUTE_FORCE,
                severity=EventSeverity.HIGH,
                event_types=[EventType.AUTH_LOGIN_FAILURE],
                threshold=10,  # 10 failed attempts
                time_window_seconds=300,  # within 5 minutes
                mitre_tactics=["Credential Access"],
                mitre_techniques=["T1110"]
            ),
        ]

        self.rules = rules

    def add_rule(self, rule: DetectionRule):
        """Add custom detection rule"""
        self.rules.append(rule)

    def analyze_event(self, event: SecurityEvent) -> list[DetectionAlert]:
        """
        Analyze a single event against all detection rules.

        Args:
            event: Event to analyze

        Returns:
            List of alerts generated
        """
        alerts = []

        # Add to history
        self._event_history.append((datetime.utcnow(), event))
        self._cleanup_history()

        # Pattern-based detection
        pattern_alerts = self._check_pattern_rules(event)
        alerts.extend(pattern_alerts)

        # Behavioral detection (requires history)
        behavior_alerts = self._check_behavioral_rules(event)
        alerts.extend(behavior_alerts)

        # Store alerts
        self.alerts.extend(alerts)

        return alerts

    def _cleanup_history(self):
        """Remove events outside the history window"""
        cutoff = datetime.utcnow() - timedelta(hours=self._max_history_hours)
        self._event_history = [
            (ts, e) for ts, e in self._event_history
            if ts > cutoff
        ]

    def _check_pattern_rules(self, event: SecurityEvent) -> list[DetectionAlert]:
        """Check pattern-based detection rules"""
        alerts = []

        for rule in self.rules:
            if not rule.enabled:
                continue

            # Check if rule applies to this event type
            if rule.event_types and event.event_type not in rule.event_types:
                continue

            # Check patterns
            if rule.patterns:
                matches = self._check_patterns(event, rule.patterns)
                if matches:
                    alert = DetectionAlert(
                        alert_id=f"alert-{datetime.utcnow().timestamp()}",
                        rule_id=rule.rule_id,
                        rule_name=rule.name,
                        detection_type=rule.detection_type,
                        severity=rule.severity,
                        timestamp=datetime.utcnow(),
                        triggering_events=[event],
                        event_count=1,
                        detection_details={
                            "matched_patterns": matches,
                            "event_description": event.description
                        },
                        confidence_score=0.8,
                        mitigation_suggestions=self._get_mitigation_suggestions(rule.detection_type)
                    )
                    alerts.append(alert)

        return alerts

    def _check_patterns(self, event: SecurityEvent, patterns: list[str]) -> list[str]:
        """Check if event matches any patterns"""
        matches = []

        # Convert event to searchable text
        text = json.dumps(event.dict(), default=str).lower()

        for pattern in patterns:
            try:
                if re.search(pattern, text, re.IGNORECASE):
                    matches.append(pattern)
            except re.error:
                # Invalid regex pattern
                continue

        return matches

    def _check_behavioral_rules(self, event: SecurityEvent) -> list[DetectionAlert]:
        """Check behavioral detection rules"""
        alerts = []

        # Check for excessive tool use
        if event.event_type in [EventType.TOOL_INVOCATION, EventType.AGENT_EXECUTION]:
            excessive_alerts = self._detect_excessive_tool_use(event)
            alerts.extend(excessive_alerts)

        # Check for bulk data access
        if event.event_type in [EventType.DATA_ACCESS_READ, EventType.DATA_EXPORT]:
            bulk_alerts = self._detect_bulk_data_access(event)
            alerts.extend(bulk_alerts)

        # Check for brute force
        if event.event_type == EventType.AUTH_LOGIN_FAILURE:
            brute_force_alerts = self._detect_brute_force(event)
            alerts.extend(brute_force_alerts)

        # Check for privilege escalation
        if event.event_type in [EventType.PRIV_ROLE_GRANTED, EventType.PRIV_PERMISSION_GRANTED]:
            escalation_alerts = self._detect_privilege_escalation(event)
            alerts.extend(escalation_alerts)

        # Check for impossible travel
        if event.event_type == EventType.AUTH_LOGIN_SUCCESS:
            travel_alerts = self._detect_impossible_travel(event)
            alerts.extend(travel_alerts)

        # Check for tool combinations
        if isinstance(event, ToolInvocationEvent):
            combo_alerts = self._detect_forbidden_tool_combinations(event)
            alerts.extend(combo_alerts)

        return alerts

    def _detect_excessive_tool_use(self, event: SecurityEvent) -> list[DetectionAlert]:
        """Detect excessive tool usage within time window"""
        alerts = []

        rule = next(
            (r for r in self.rules if r.detection_type == DetectionType.EXCESSIVE_TOOL_USE),
            None
        )
        if not rule or not rule.threshold or not rule.time_window_seconds:
            return alerts

        # Count tool invocations by actor in time window
        cutoff = datetime.utcnow() - timedelta(seconds=rule.time_window_seconds)
        user_events = [
            e for ts, e in self._event_history
            if ts > cutoff
            and e.actor_user_id == event.actor_user_id
            and e.event_type in [EventType.TOOL_INVOCATION, EventType.AGENT_EXECUTION]
        ]

        if len(user_events) >= rule.threshold:
            alert = DetectionAlert(
                alert_id=f"alert-{datetime.utcnow().timestamp()}",
                rule_id=rule.rule_id,
                rule_name=rule.name,
                detection_type=rule.detection_type,
                severity=rule.severity,
                timestamp=datetime.utcnow(),
                triggering_events=user_events[-10:],  # Last 10 events
                event_count=len(user_events),
                detection_details={
                    "tool_count": len(user_events),
                    "threshold": rule.threshold,
                    "time_window_seconds": rule.time_window_seconds,
                    "user_id": event.actor_user_id
                },
                confidence_score=0.9,
                mitigation_suggestions=[
                    "Temporarily rate-limit tool usage for this user",
                    "Investigate if user account is compromised",
                    "Require re-authentication"
                ]
            )
            alerts.append(alert)

        return alerts

    def _detect_bulk_data_access(self, event: SecurityEvent) -> list[DetectionAlert]:
        """Detect bulk data access patterns"""
        alerts = []

        rule = next(
            (r for r in self.rules if r.detection_type == DetectionType.BULK_DATA_ACCESS),
            None
        )
        if not rule or not rule.threshold or not rule.time_window_seconds:
            return alerts

        # Sum record counts in time window
        cutoff = datetime.utcnow() - timedelta(seconds=rule.time_window_seconds)
        user_data_events = [
            e for ts, e in self._event_history
            if ts > cutoff
            and e.actor_user_id == event.actor_user_id
            and e.event_type in [EventType.DATA_ACCESS_READ, EventType.DATA_EXPORT]
        ]

        total_records = 0
        for e in user_data_events:
            if isinstance(e, DataAccessEvent):
                total_records += e.record_count or 0

        if total_records >= rule.threshold:
            alert = DetectionAlert(
                alert_id=f"alert-{datetime.utcnow().timestamp()}",
                rule_id=rule.rule_id,
                rule_name=rule.name,
                detection_type=rule.detection_type,
                severity=rule.severity,
                timestamp=datetime.utcnow(),
                triggering_events=user_data_events[-5:],
                event_count=len(user_data_events),
                detection_details={
                    "total_records": total_records,
                    "threshold": rule.threshold,
                    "time_window_seconds": rule.time_window_seconds,
                    "user_id": event.actor_user_id
                },
                confidence_score=0.85,
                mitigation_suggestions=[
                    "Block export functionality temporarily",
                    "Contact user to verify legitimacy",
                    "Review audit logs for data accessed"
                ]
            )
            alerts.append(alert)

        return alerts

    def _detect_brute_force(self, event: SecurityEvent) -> list[DetectionAlert]:
        """Detect brute force login attempts"""
        alerts = []

        rule = next(
            (r for r in self.rules if r.detection_type == DetectionType.BRUTE_FORCE),
            None
        )
        if not rule or not rule.threshold or not rule.time_window_seconds:
            return alerts

        # Count failed logins for IP/username
        cutoff = datetime.utcnow() - timedelta(seconds=rule.time_window_seconds)
        failed_logins = [
            e for ts, e in self._event_history
            if ts > cutoff
            and e.actor_ip_address == event.actor_ip_address
            and e.event_type == EventType.AUTH_LOGIN_FAILURE
        ]

        if len(failed_logins) >= rule.threshold:
            alert = DetectionAlert(
                alert_id=f"alert-{datetime.utcnow().timestamp()}",
                rule_id=rule.rule_id,
                rule_name=rule.name,
                detection_type=rule.detection_type,
                severity=rule.severity,
                timestamp=datetime.utcnow(),
                triggering_events=failed_logins[-10:],
                event_count=len(failed_logins),
                detection_details={
                    "failed_attempts": len(failed_logins),
                    "threshold": rule.threshold,
                    "ip_address": event.actor_ip_address,
                    "target_usernames": list(set(e.actor_username for e in failed_logins if e.actor_username))
                },
                confidence_score=0.95,
                mitigation_suggestions=[
                    "Block IP address temporarily",
                    "Implement CAPTCHA",
                    "Increase account lockout threshold"
                ]
            )
            alerts.append(alert)

        return alerts

    def _detect_privilege_escalation(self, event: SecurityEvent) -> list[DetectionAlert]:
        """Detect rapid privilege escalation"""
        alerts = []

        # Check for multiple privilege changes by same actor in short time
        cutoff = datetime.utcnow() - timedelta(minutes=10)
        actor_priv_changes = [
            e for ts, e in self._event_history
            if ts > cutoff
            and e.actor_user_id == event.actor_user_id
            and e.event_type in [EventType.PRIV_ROLE_GRANTED, EventType.PRIV_PERMISSION_GRANTED]
        ]

        if len(actor_priv_changes) > 5:
            rule = next(
                (r for r in self.rules if r.detection_type == DetectionType.PRIVILEGE_ESCALATION),
                None
            )
            if rule:
                alert = DetectionAlert(
                    alert_id=f"alert-{datetime.utcnow().timestamp()}",
                    rule_id=rule.rule_id,
                    rule_name=rule.name,
                    detection_type=rule.detection_type,
                    severity=rule.severity,
                    timestamp=datetime.utcnow(),
                    triggering_events=actor_priv_changes,
                    event_count=len(actor_priv_changes),
                    detection_details={
                        "privilege_changes": len(actor_priv_changes),
                        "actor_user_id": event.actor_user_id,
                        "affected_users": list(set(
                            e.target_user_id for e in actor_priv_changes
                            if hasattr(e, "target_user_id")
                        ))
                    },
                    confidence_score=0.9,
                    mitigation_suggestions=[
                        "Revoke recent privilege changes pending review",
                        "Require additional approval for further changes",
                        "Investigate actor account for compromise"
                    ]
                )
                alerts.append(alert)

        return alerts

    def _detect_impossible_travel(self, event: SecurityEvent) -> list[DetectionAlert]:
        """Detect impossible travel between login locations"""
        alerts = []

        if not event.actor_user_id:
            return alerts

        # Find recent logins by this user
        cutoff = datetime.utcnow() - timedelta(hours=1)
        user_logins = [
            (ts, e)
            for ts, e in self._event_history
            if ts > cutoff
            and e.actor_user_id == event.actor_user_id
            and e.event_type == EventType.AUTH_LOGIN_SUCCESS
            and e.latitude is not None
            and e.longitude is not None
        ]

        # Check for impossible travel (faster than 900 km/h ~ aircraft speed)
        # Using 500 km/h as conservative threshold
        for prev_ts, prev_event in user_logins:
            if not (prev_event.latitude and prev_event.longitude and event.latitude and event.longitude):
                continue

            # Calculate distance using Haversine formula
            distance_km = self._haversine_distance(
                prev_event.latitude, prev_event.longitude,
                event.latitude, event.longitude
            )

            time_diff_hours = (event.timestamp - prev_ts).total_seconds() / 3600

            if time_diff_hours > 0:
                speed_kmh = distance_km / time_diff_hours

                if speed_kmh > 900:  # Faster than commercial aircraft
                    rule = next(
                        (r for r in self.rules if r.detection_type == DetectionType.IMPOSSIBLE_TRAVEL),
                        None
                    )
                    if rule:
                        alert = DetectionAlert(
                            alert_id=f"alert-{datetime.utcnow().timestamp()}",
                            rule_id=rule.rule_id,
                            rule_name=rule.name,
                            detection_type=rule.detection_type,
                            severity=rule.severity,
                            timestamp=datetime.utcnow(),
                            triggering_events=[prev_event, event],
                            event_count=2,
                            detection_details={
                                "distance_km": round(distance_km, 2),
                                "time_diff_hours": round(time_diff_hours, 2),
                                "speed_kmh": round(speed_kmh, 2),
                                "user_id": event.actor_user_id,
                                "location1": f"({prev_event.latitude}, {prev_event.longitude})",
                                "location2": f"({event.latitude}, {event.longitude})"
                            },
                            confidence_score=0.95,
                            mitigation_suggestions=[
                                "Revoke current session",
                                "Require MFA verification",
                                "Contact user to verify identity",
                                "Consider account compromise"
                            ]
                        )
                        alerts.append(alert)

        return alerts

    def _detect_forbidden_tool_combinations(self, event: ToolInvocationEvent) -> list[DetectionAlert]:
        """Detect dangerous tool combinations"""
        alerts = []

        # Check for information gathering followed by data export
        cutoff = datetime.utcnow() - timedelta(minutes=5)
        user_tools = [
            e for ts, e in self._event_history
            if ts > cutoff
            and e.actor_user_id == event.actor_user_id
            and isinstance(e, ToolInvocationEvent)
        ]

        # Get unique tools used
        tools_used = set(e.tool_name for e in user_tools)

        # Forbidden combinations
        forbidden_combos = [
            ({
                "database_query", "file_write", "base64_encode"
            }, "Potential data exfiltration via database query + encoding + file write"),
            ({
                "file_read", "http_request", "encryption"
            }, "Potential data exfiltration via file read + encryption + external HTTP request"),
            ({
                "list_users", "export_data", "email_send"
            }, "Potential user data harvesting + exfiltration via email"),
            ({
                "execute_command", "file_read", "network_connect"
            }, "Potential remote code execution + data exfiltration"),
        ]

        for combo_tools, description in forbidden_combos:
            if combo_tools.issubset(tools_used):
                rule = next(
                    (r for r in self.rules if r.detection_type == DetectionType.FORBIDDEN_TOOL_COMBINATION),
                    None
                )
                if rule:
                    alert = DetectionAlert(
                        alert_id=f"alert-{datetime.utcnow().timestamp()}",
                        rule_id=rule.rule_id,
                        rule_name=rule.name,
                        detection_type=rule.detection_type,
                        severity=rule.severity,
                        timestamp=datetime.utcnow(),
                        triggering_events=user_tools[-5:],
                        event_count=len(user_tools),
                        detection_details={
                            "tools_used": list(tools_used),
                            "forbidden_pattern": list(combo_tools),
                            "description": description,
                            "user_id": event.actor_user_id
                        },
                        confidence_score=0.85,
                        mitigation_suggestions=[
                            "Block current operation",
                            "Investigate user intent",
                            "Review tool usage history"
                        ]
                    )
                    alerts.append(alert)

        return alerts

    def _haversine_distance(self, lat1: float, lon1: float, lat2: float, lon2: float) -> float:
        """Calculate distance between two coordinates using Haversine formula"""
        from math import asin, cos, radians, sin, sqrt

        R = 6371  # Earth radius in km

        lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
        dlat = lat2 - lat1
        dlon = lon2 - lon1

        a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
        c = 2 * asin(sqrt(a))

        return R * c

    def _get_mitigation_suggestions(self, detection_type: DetectionType) -> list[str]:
        """Get mitigation suggestions for detection type"""
        suggestions = {
            DetectionType.PROMPT_INJECTION: [
                "Sanitize all user inputs before passing to model",
                "Use instruction-following models trained against injection",
                "Implement output validation and filtering",
                "Monitor for suspicious model responses"
            ],
            DetectionType.INDIRECT_INJECTION: [
                "Validate and sanitize data from external sources",
                "Implement content security policies",
                "Use sandboxed environments for untrusted content",
                "Implement strict output filtering"
            ],
            DetectionType.JAILBREAK_ATTEMPT: [
                "Use models with robust safety training",
                "Implement additional prompt context for safety",
                "Monitor for and block role-play scenarios",
                "Regular safety audits of model interactions"
            ],
            DetectionType.DATA_EXFILTRATION: [
                "Block export functionality",
                "Revoke access pending investigation",
                "Contact user to verify legitimacy",
                "Review all recent access by this user"
            ],
            DetectionType.ABNORMAL_TOOL_CALL: [
                "Review tool parameters for malicious content",
                "Block suspicious tool invocations",
                "Require additional authentication",
                "Escalate to security team"
            ],
            DetectionType.BRUTE_FORCE: [
                "Block IP address temporarily",
                "Implement account lockout policy",
                "Add CAPTCHA challenges",
                "Monitor for continued attempts"
            ],
        }

        return suggestions.get(detection_type, ["Review event details", "Escalate if confirmed"])

    def get_alerts(
        self,
        severity: EventSeverity | None = None,
        limit: int = 100
    ) -> list[DetectionAlert]:
        """Get alerts, optionally filtered by severity"""
        alerts = self.alerts

        if severity:
            alerts = [a for a in alerts if a.severity == severity]

        # Return most recent first
        alerts = sorted(alerts, key=lambda a: a.timestamp, reverse=True)

        return alerts[:limit]

    def get_stats(self) -> dict[str, Any]:
        """Get detection statistics"""
        alert_counts = defaultdict(int)
        for alert in self.alerts:
            alert_counts[alert.detection_type.value] += 1

        return {
            "total_rules": len(self.rules),
            "enabled_rules": len([r for r in self.rules if r.enabled]),
            "total_alerts": len(self.alerts),
            "alerts_by_type": dict(alert_counts),
            "events_in_history": len(self._event_history),
            "history_window_hours": self._max_history_hours
        }


# Singleton instance
_default_detector = None


def get_detector() -> SecurityEventDetector:
    """Get default detector instance"""
    global _default_detector
    if _default_detector is None:
        _default_detector = SecurityEventDetector()
    return _default_detector
