#!/usr/bin/env python3
"""
AI Engineering Prompts Web Interface
A beautiful Flask-based web UI for browsing and managing prompts
"""

import json
from pathlib import Path

from flask import Flask, jsonify, render_template, request, send_file
from flask_cors import CORS
from prompt_engineer import PromptEngineer

app = Flask(__name__)
CORS(app)

# Initialize PromptEngineer
pe = PromptEngineer()

# Constants
TEMPLATE_DIR = Path(__file__).parent / "templates"
STATIC_DIR = Path(__file__).parent / "static"


@app.route("/")
def index():
    """Render the main web interface"""
    return render_template("index.html")


@app.route("/api/categories")
def get_categories():
    """Get all categories"""
    categories = pe.list_categories()
    return jsonify({"success": True, "categories": categories})


@app.route("/api/categories/<category_id>")
def get_category(category_id):
    """Get a specific category"""
    category = pe.get_category(category_id)
    if category:
        return jsonify({"success": True, "category": category})
    else:
        return jsonify({"success": False, "error": "Category not found"}), 404


@app.route("/api/prompts")
def get_prompts():
    """Get all prompts with optional filtering"""
    scope = request.args.get("scope")
    complexity = request.args.get("complexity")
    category_id = request.args.get("category_id")

    if category_id:
        # Get prompts from specific category
        category = pe.get_category(category_id)
        if category:
            prompts = [{**p, "category": category} for p in category.get("prompts", [])]
        else:
            prompts = []
    elif scope:
        # Filter by scope
        prompts = pe.filter_by_scope(scope)
    elif complexity:
        # Filter by complexity
        prompts = pe.filter_by_complexity(complexity)
    else:
        # Get all prompts
        prompts = []
        for category in pe.list_categories():
            for prompt in category.get("prompts", []):
                prompts.append({**prompt, "category": category})

    return jsonify({"success": True, "prompts": prompts, "count": len(prompts)})


@app.route("/api/prompts/<prompt_id>")
def get_prompt(prompt_id):
    """Get a specific prompt"""
    prompt = pe.get_prompt(prompt_id)
    if prompt:
        return jsonify({"success": True, "prompt": prompt})
    else:
        return jsonify({"success": False, "error": "Prompt not found"}), 404


@app.route("/api/search")
def search_prompts():
    """Search prompts"""
    query = request.args.get("q", "")
    if not query:
        return jsonify({"success": False, "error": "Query parameter required"}), 400

    results = pe.search_prompts(query)
    return jsonify(
        {"success": True, "results": results, "count": len(results), "query": query}
    )


@app.route("/api/stats")
def get_stats():
    """Get registry statistics"""
    categories = pe.list_categories()
    total_prompts = sum(len(c.get("prompts", [])) for c in categories)

    complexity_counts = {"low": 0, "medium": 0, "high": 0}
    scope_counts = {}

    for category in categories:
        for prompt in category.get("prompts", []):
            complexity = prompt.get("complexity", "unknown")
            if complexity in complexity_counts:
                complexity_counts[complexity] += 1

            for scope in prompt.get("scope", []):
                scope_counts[scope] = scope_counts.get(scope, 0) + 1

    return jsonify(
        {
            "success": True,
            "stats": {
                "total_categories": len(categories),
                "total_prompts": total_prompts,
                "complexity_distribution": complexity_counts,
                "scope_distribution": scope_counts,
            },
        }
    )


@app.route("/api/export/<prompt_id>")
def export_prompt(prompt_id):
    """Export a prompt as Markdown"""
    prompt = pe.get_prompt(prompt_id)
    if not prompt:
        return jsonify({"success": False, "error": "Prompt not found"}), 404

    # Generate markdown content
    content = f"""# {prompt['name']}

**ID:** {prompt['id']}
**Category:** {prompt.get('category', {}).get('name', 'N/A')}
**Complexity:** {prompt.get('complexity', 'unknown').upper()}
**Estimated Time:** {prompt.get('estimated_time', 'N/A')}
**Scope:** {', '.join(prompt.get('scope', []))}

## Prompt

{prompt['prompt']}

---

*Generated by PsychSync AI Engineering Prompts*
"""

    # Save to temporary file
    temp_file = Path(f"/tmp/{prompt_id}.md")
    temp_file.write_text(content)

    return send_file(
        temp_file,
        as_attachment=True,
        download_name=f"{prompt_id}.md",
        mimetype="text/markdown",
    )


def create_templates():
    """Create HTML templates for the web interface"""
    # Create index.html
    index_html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🤖 PsychSync AI Engineering Prompts</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        :root {
            --primary: #6366f1;
            --primary-dark: #4f46e5;
            --secondary: #8b5cf6;
            --success: #10b981;
            --warning: #f59e0b;
            --danger: #ef4444;
            --dark: #1f2937;
            --light: #f9fafb;
            --border: #e5e7eb;
            --text: #374151;
            --text-light: #6b7280;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
            color: var(--text);
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
        }

        .header {
            background: white;
            border-radius: 16px;
            padding: 30px;
            margin-bottom: 30px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.1);
            text-align: center;
        }

        .header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }

        .stat-card {
            background: var(--light);
            padding: 20px;
            border-radius: 12px;
            text-align: center;
        }

        .stat-value {
            font-size: 2.5em;
            font-weight: bold;
            color: var(--primary);
        }

        .stat-label {
            color: var(--text-light);
            margin-top: 5px;
        }

        .controls {
            background: white;
            border-radius: 16px;
            padding: 25px;
            margin-bottom: 30px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
        }

        .search-box {
            width: 100%;
            padding: 15px 20px;
            border: 2px solid var(--border);
            border-radius: 12px;
            font-size: 16px;
            transition: all 0.3s;
        }

        .search-box:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1);
        }

        .filters {
            display: flex;
            gap: 15px;
            margin-top: 20px;
            flex-wrap: wrap;
        }

        .filter-select {
            padding: 10px 15px;
            border: 2px solid var(--border);
            border-radius: 8px;
            font-size: 14px;
            background: white;
            cursor: pointer;
            transition: all 0.3s;
        }

        .filter-select:hover {
            border-color: var(--primary);
        }

        .categories {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }

        .category-card {
            background: white;
            border-radius: 16px;
            padding: 25px;
            cursor: pointer;
            transition: all 0.3s;
            box-shadow: 0 4px 15px rgba(0,0,0,0.08);
        }

        .category-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(0,0,0,0.15);
        }

        .category-icon {
            font-size: 3em;
            margin-bottom: 15px;
        }

        .category-name {
            font-size: 1.3em;
            font-weight: bold;
            margin-bottom: 10px;
            color: var(--dark);
        }

        .category-description {
            color: var(--text-light);
            line-height: 1.5;
        }

        .prompt-count {
            display: inline-block;
            background: var(--primary);
            color: white;
            padding: 5px 12px;
            border-radius: 20px;
            font-size: 0.9em;
            margin-top: 15px;
        }

        .prompts {
            display: grid;
            gap: 20px;
        }

        .prompt-card {
            background: white;
            border-radius: 12px;
            padding: 25px;
            cursor: pointer;
            transition: all 0.3s;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        }

        .prompt-card:hover {
            box-shadow: 0 5px 20px rgba(0,0,0,0.1);
        }

        .prompt-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
        }

        .prompt-name {
            font-size: 1.2em;
            font-weight: bold;
            color: var(--dark);
        }

        .complexity {
            padding: 5px 12px;
            border-radius: 20px;
            font-size: 0.85em;
            font-weight: 600;
        }

        .complexity.low {
            background: #d1fae5;
            color: #065f46;
        }

        .complexity.medium {
            background: #fef3c7;
            color: #92400e;
        }

        .complexity.high {
            background: #fee2e2;
            color: #991b1b;
        }

        .prompt-meta {
            display: flex;
            gap: 20px;
            color: var(--text-light);
            font-size: 0.9em;
        }

        .modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0,0,0,0.7);
            z-index: 1000;
            padding: 20px;
            overflow-y: auto;
        }

        .modal.active {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .modal-content {
            background: white;
            border-radius: 20px;
            padding: 40px;
            max-width: 800px;
            max-height: 90vh;
            overflow-y: auto;
        }

        .modal-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
        }

        .modal-title {
            font-size: 2em;
            font-weight: bold;
        }

        .close-btn {
            background: var(--border);
            border: none;
            width: 40px;
            height: 40px;
            border-radius: 50%;
            cursor: pointer;
            font-size: 1.5em;
            transition: all 0.3s;
        }

        .close-btn:hover {
            background: var(--danger);
            color: white;
        }

        .prompt-content {
            background: var(--light);
            padding: 25px;
            border-radius: 12px;
            margin: 20px 0;
            line-height: 1.8;
            white-space: pre-wrap;
        }

        .export-btn {
            background: var(--primary);
            color: white;
            border: none;
            padding: 12px 25px;
            border-radius: 8px;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.3s;
        }

        .export-btn:hover {
            background: var(--primary-dark);
            transform: translateY(-2px);
        }

        .hidden {
            display: none;
        }

        .btn {
            background: var(--primary);
            color: white;
            border: none;
            padding: 12px 25px;
            border-radius: 8px;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.3s;
        }

        .btn:hover {
            background: var(--primary-dark);
            transform: translateY(-2px);
        }

        .btn-secondary {
            background: white;
            color: var(--primary);
            border: 2px solid var(--primary);
        }

        .btn-secondary:hover {
            background: var(--primary);
            color: white;
        }

        .back-btn {
            margin-bottom: 20px;
        }

        @media (max-width: 768px) {
            .header h1 {
                font-size: 1.8em;
            }

            .stats {
                grid-template-columns: 1fr;
            }

            .categories {
                grid-template-columns: 1fr;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🤖 PsychSync AI Engineering Prompts</h1>
            <p style="font-size: 1.2em; color: var(--text-light);">
                Comprehensive AI-Powered Codebase Analysis
            </p>
            <div class="stats" id="stats"></div>
        </div>

        <div class="controls">
            <input
                type="text"
                class="search-box"
                id="searchInput"
                placeholder="🔍 Search prompts by keyword..."
            >
            <div class="filters">
                <select class="filter-select" id="scopeFilter">
                    <option value="">All Scopes</option>
                    <option value="backend">Backend</option>
                    <option value="frontend">Frontend</option>
                    <option value="api">API</option>
                    <option value="database">Database</option>
                    <option value="testing">Testing</option>
                    <option value="security">Security</option>
                    <option value="devops">DevOps</option>
                </select>
                <select class="filter-select" id="complexityFilter">
                    <option value="">All Complexities</option>
                    <option value="low">Low</option>
                    <option value="medium">Medium</option>
                    <option value="high">High</option>
                </select>
                <button class="btn btn-secondary" onclick="resetFilters()">Reset Filters</button>
            </div>
        </div>

        <div id="mainContent">
            <div class="categories" id="categories"></div>
        </div>

        <div id="promptsView" class="hidden">
            <button class="btn btn-secondary back-btn" onclick="showCategories()">← Back to Categories</button>
            <h2 id="categoryTitle" style="margin-bottom: 20px; color: var(--dark);"></h2>
            <div class="prompts" id="prompts"></div>
        </div>
    </div>

    <div class="modal" id="promptModal">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="modalTitle"></h2>
                <button class="close-btn" onclick="closeModal()">×</button>
            </div>
            <div id="modalBody"></div>
        </div>
    </div>

    <script>
        let currentCategory = null;
        let allPrompts = [];

        // Load statistics
        async function loadStats() {
            const response = await fetch('/api/stats');
            const data = await response.json();

            const statsHtml = `
                <div class="stat-card">
                    <div class="stat-value">${data.stats.total_categories}</div>
                    <div class="stat-label">Categories</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">${data.stats.total_prompts}</div>
                    <div class="stat-label">Total Prompts</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">${data.stats.complexity_distribution.high}</div>
                    <div class="stat-label">High Complexity</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">${data.stats.complexity_distribution.medium}</div>
                    <div class="stat-label">Medium Complexity</div>
                </div>
            `;

            document.getElementById('stats').innerHTML = statsHtml;
        }

        // Load categories
        async function loadCategories() {
            const response = await fetch('/api/categories');
            const data = await response.json();

            const categoriesHtml = data.categories.map(cat => `
                <div class="category-card" onclick="loadPrompts('${cat.id}')">
                    <div class="category-icon">${cat.icon}</div>
                    <div class="category-name">${cat.name}</div>
                    <div class="category-description">${cat.description}</div>
                    <div class="prompt-count">${cat.prompts.length} prompts</div>
                </div>
            `).join('');

            document.getElementById('categories').innerHTML = categoriesHtml;
        }

        // Load prompts for a category
        async function loadPrompts(categoryId, isSearch = false) {
            let url = `/api/prompts?category_id=${categoryId}`;
            if (isSearch) {
                url = `/api/prompts`;
            }

            const response = await fetch(url);
            const data = await response.json();

            allPrompts = data.prompts;

            if (!isSearch) {
                const category = await getCategory(categoryId);
                currentCategory = category;
                document.getElementById('categoryTitle').textContent = `${category.icon} ${category.name}`;
                document.getElementById('mainContent').classList.add('hidden');
                document.getElementById('promptsView').classList.remove('hidden');
            }

            renderPrompts(allPrompts);
        }

        // Get category details
        async function getCategory(categoryId) {
            const response = await fetch(`/api/categories/${categoryId}`);
            const data = await response.json();
            return data.category;
        }

        // Render prompts
        function renderPrompts(prompts) {
            const filteredPrompts = applyFilters(prompts);

            const promptsHtml = filteredPrompts.map(prompt => `
                <div class="prompt-card" onclick='showPrompt(${JSON.stringify(prompt).replace(/'/g, "\\'")})'>
                    <div class="prompt-header">
                        <div class="prompt-name">${prompt.name}</div>
                        <div class="complexity ${prompt.complexity}">${prompt.complexity.toUpperCase()}</div>
                    </div>
                    <div class="prompt-meta">
                        <span>⏱️ ${prompt.estimated_time}</span>
                        <span>🎯 ${prompt.scope.join(', ')}</span>
                    </div>
                </div>
            `).join('');

            document.getElementById('prompts').innerHTML = promptsHtml || '<p style="text-align: center; color: var(--text-light);">No prompts found.</p>';
        }

        // Apply filters
        function applyFilters(prompts) {
            const scope = document.getElementById('scopeFilter').value;
            const complexity = document.getElementById('complexityFilter').value;

            return prompts.filter(prompt => {
                if (scope && !prompt.scope.includes(scope)) return false;
                if (complexity && prompt.complexity !== complexity) return false;
                return true;
            });
        }

        // Show prompt details
        function showPrompt(prompt) {
            document.getElementById('modalTitle').textContent = prompt.name;

            const modalBody = `
                <div style="margin-bottom: 20px;">
                    <strong>Category:</strong> ${prompt.category.name}<br>
                    <strong>Complexity:</strong> ${prompt.complexity.toUpperCase()}<br>
                    <strong>Estimated Time:</strong> ${prompt.estimated_time}<br>
                    <strong>Scope:</strong> ${prompt.scope.join(', ')}
                </div>
                <div class="prompt-content">${prompt.prompt}</div>
                <button class="export-btn" onclick="exportPrompt('${prompt.id}')">
                    📥 Export as Markdown
                </button>
            `;

            document.getElementById('modalBody').innerHTML = modalBody;
            document.getElementById('promptModal').classList.add('active');
        }

        // Close modal
        function closeModal() {
            document.getElementById('promptModal').classList.remove('active');
        }

        // Export prompt
        function exportPrompt(promptId) {
            window.open(`/api/export/${promptId}`, '_blank');
        }

        // Show categories view
        function showCategories() {
            document.getElementById('mainContent').classList.remove('hidden');
            document.getElementById('promptsView').classList.add('hidden');
            currentCategory = null;
        }

        // Reset filters
        function resetFilters() {
            document.getElementById('scopeFilter').value = '';
            document.getElementById('complexityFilter').value = '';
            document.getElementById('searchInput').value = '';

            if (currentCategory) {
                loadPrompts(currentCategory.id);
            } else {
                loadCategories();
            }
        }

        // Search functionality
        let searchTimeout;
        document.getElementById('searchInput').addEventListener('input', (e) => {
            clearTimeout(searchTimeout);
            searchTimeout = setTimeout(async () => {
                const query = e.target.value.trim();

                if (query.length < 2) {
                    if (currentCategory) {
                        loadPrompts(currentCategory.id);
                    } else {
                        showCategories();
                    }
                    return;
                }

                const response = await fetch(`/api/search?q=${encodeURIComponent(query)}`);
                const data = await response.json();

                document.getElementById('categoryTitle').textContent = `🔍 Search Results: "${query}"`;
                document.getElementById('mainContent').classList.add('hidden');
                document.getElementById('promptsView').classList.remove('hidden');

                allPrompts = data.results;
                renderPrompts(allPrompts);
            }, 300);
        });

        // Filter change handlers
        document.getElementById('scopeFilter').addEventListener('change', () => {
            if (allPrompts.length) renderPrompts(allPrompts);
        });

        document.getElementById('complexityFilter').addEventListener('change', () => {
            if (allPrompts.length) renderPrompts(allPrompts);
        });

        // Close modal on outside click
        document.getElementById('promptModal').addEventListener('click', (e) => {
            if (e.target.id === 'promptModal') {
                closeModal();
            }
        });

        // Initialize
        loadStats();
        loadCategories();
    </script>
</body>
</html>"""

    (TEMPLATE_DIR / "index.html").write_text(index_html)

    print("✅ Created web interface templates")


if __name__ == "__main__":
    # Create necessary directories
    TEMPLATE_DIR.mkdir(exist_ok=True)
    STATIC_DIR.mkdir(exist_ok=True)

    # Check if templates exist, if not create them
    if not (TEMPLATE_DIR / "index.html").exists():
        create_templates()

    print(
        """
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║   🤖 PsychSync AI Engineering Prompts - Web Interface        ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝

🌐 Web Interface: http://localhost:5000
📚 API Documentation: http://localhost:5000/api/docs
🚀 Ready to serve prompts!

    """
    )

    app.run(host="0.0.0.0", port=5000, debug=True)
