#!/bin/bash

################################################################################
# Ubuntu Server Hardening Script for SaaS Production
# Purpose: Automate security hardening of Ubuntu servers for production use
# Based on: CIS Benchmark, NIST 800-53, PCI DSS Requirements
#
# Usage: sudo bash harden-ubuntu-server.sh
#
# WARNING: This script makes significant changes to your server configuration.
# Review and test in a non-production environment first!
################################################################################

set -euo pipefail  # Exit on error, undefined vars, pipe failures

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging
LOG_FILE="/var/log/server_hardening_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$LOG_FILE")
exec 2>&1

################################################################################
# Helper Functions
################################################################################

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

backup_file() {
    local file=$1
    if [[ -f "$file" ]]; then
        local backup_dir="/root/backups/hardening_$(date +%Y%m%d)"
        mkdir -p "$backup_dir"
        cp "$file" "$backup_dir/$(basename $file).bak"
        log_success "Backed up $file to $backup_dir"
    fi
}

################################################################################
# Installation Functions
################################################################################

install_security_tools() {
    log_info "Installing security tools..."

    apt-get update -qq

    # Install essential security packages
    apt-get install -y \
        fail2ban \
        ufw \
        auditd \
        rsyslog \
        logrotate \
        unattended-upgrades \
        apt-listbugs \
        apt-listchanges \
        libpam-pwquality \
        libpam-tmpdir \
        rkhunter \
        chkrootkit \
        lynis \
        needrestart \
        haveged \
        certbot \
        aide \
        debsums \
        systemd-coredump

    log_success "Security tools installed"
}

################################################################################
# SSH Hardening
################################################################################

harden_ssh() {
    log_info "Hardening SSH configuration..."

    local sshd_config="/etc/ssh/sshd_config"
    backup_file "$sshd_config"

    # Create hardened SSH config
    cat > "$sshd_config" << 'EOF'
# SSH Hardened Configuration
# Generated by harden-ubuntu-server.sh

# Only protocol 2
Protocol 2

# Port configuration (CHANGE THIS TO NON-STANDARD PORT)
# Port 22
Port 2222

# Listen address
# ListenAddress 0.0.0.0
ListenAddress 0.0.0.0

# Host key files
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and MACs (only secure ones)
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr
MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256

# Logging
SyslogFacility AUTHPRIV
LogLevel VERBOSE

# Authentication
LoginGraceTime 60
PermitRootLogin no
StrictModes yes
MaxAuthTries 3
MaxSessions 2
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Session
X11Forwarding no
X11UseLocalhost yes
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
UseDNS no

# Security options
AllowTcpForwarding no
GatewayPorts no
PermitTunnel no
AllowAgentForwarding no

# Client alive settings (detect inactive sessions)
ClientAliveInterval 300
ClientAliveCountMax 3

# Disable vulnerable features
HostbasedAuthentication no
IgnoreRhosts yes
RhostsRSAAuthentication no

# PAM
UsePAM yes

# Restrict users (uncomment and modify)
# AllowUsers user1 user2 user3

# Force key algorithms
HostKeyAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp521

# Banner
# Banner /etc/issue.net

# SFTP subsystem
Subsystem sftp internal-sftp
EOF

    # Restart SSH with testing first
    log_info "Testing SSH configuration..."
    if sshd -t 0<&1; then
        systemctl restart sshd
        log_success "SSH hardened and restarted"
    else
        log_error "SSH configuration test failed. Restoring backup..."
        # Restore from backup if available
        cp /root/backups/hardening_*/sshd_config.bak /etc/ssh/sshd_config
        exit 1
    fi
}

################################################################################
# Firewall Configuration
################################################################################

configure_firewall() {
    log_info "Configuring UFW firewall..."

    # Reset firewall to default
    ufw --force reset

    # Set default policies
    ufw default deny incoming
    ufw default allow outgoing

    # Allow SSH (CHANGE PORT IF CUSTOM)
    ufw allow 2222/tcp comment 'SSH'

    # Allow HTTP/HTTPS (if web server)
    ufw allow 80/tcp comment 'HTTP'
    ufw allow 443/tcp comment 'HTTPS'

    # Allow FastAPI backend (if needed)
    ufw allow 8000/tcp comment 'FastAPI'

    # Rate limiting for SSH
    ufw limit 2222/tcp comment 'SSH rate limit'

    # Enable logging
    ufw logging on

    # Enable firewall
    echo "y" | ufw enable

    # Show status
    ufw status verbose

    log_success "Firewall configured and enabled"
}

################################################################################
# Fail2Ban Configuration
################################################################################

configure_fail2ban() {
    log_info "Configuring Fail2Ban..."

    local jail_local="/etc/fail2ban/jail.local"

    # Create custom Fail2Ban configuration
    cat > "$jail_local" << 'EOF'
[DEFAULT]
# Default configuration for all jails

# Ban time: 24 hours
bantime = 86400

# Find time: 10 minutes
findtime = 600

# Max retries: 3 attempts
maxretry = 3

# Destination email for notifications
destemail = security@yourdomain.com
sendername = Fail2Ban-$(hostname)
sender = fail2ban@$(hostname)

# Action to take
action = %(action_mwl)s

# Ignore IP addresses (whitelist)
ignoreip = 127.0.0.1/8

[sshd]
enabled = true
port = 2222
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 86400
findtime = 600

[sshd-ddos]
enabled = true
port = 2222
filter = sshd-ddos
logpath = /var/log/auth.log
maxretry = 2
findtime = 300
bantime = 86400

[nginx-http-auth]
enabled = true
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 5
findtime = 600
bantime = 86400

[nginx-noscript]
enabled = true
filter = nginx-noscript
logpath = /var/log/nginx/access.log
maxretry = 3
findtime = 300
bantime = 86400

[nginx-badbots]
enabled = true
filter = nginx-badbots
logpath = /var/log/nginx/access.log
maxretry = 2
findtime = 600
bantime = 86400

[nginx-noproxy]
enabled = true
filter = nginx-noproxy
logpath = /var/log/nginx/access.log
maxretry = 2
findtime = 300
bantime = 86400

[recidive]
enabled = true
filter = recidive
logpath = /var/log/fail2ban.log
action = %(action_mwl)s
bantime = 2592000  # 30 days
findtime = 86400
maxretry = 5

[apache-auth]
enabled = false
filter = apache-auth
logpath = /var/log/apache2/error.log
maxretry = 3
EOF

    # Restart Fail2Ban
    systemctl enable fail2ban
    systemctl restart fail2ban

    # Show status
    fail2ban-client status

    log_success "Fail2Ban configured and enabled"
}

################################################################################
# Kernel Hardening
################################################################################

harden_kernel() {
    log_info "Hardening kernel parameters..."

    local sysctl_conf="/etc/sysctl.d/99-security-hardening.conf"

    cat > "$sysctl_conf" << 'EOF'
################################################################################
# Kernel Security Hardening
# Generated by harden-ubuntu-server.sh
################################################################################

# IP Source Routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Send Redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# ICMP Redirect Acceptance
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Secure ICMP Redirect Acceptance
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0

# Log Spoofed Packets, Source Routed Packets, Redirect Packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Ignore ICMP Broadcast Requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore Bogus ICMP Errors
net.ipv4.icmp_ignore_bogus_error_responses = 1

# TCP SYN Cookies
net.ipv4.tcp_syncookies = 1

# TCP RFC 1337
net.ipv4.tcp_rfc1337 = 1

# IP Forwarding
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# TCP Timestamps
net.ipv4.tcp_timestamps = 0

# TCP SYN Cookies Protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# TCP Keep-Alive
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 5

# TCP FIN Timeout
net.ipv4.tcp_fin_timeout = 30

# TCP TW Reuse
net.ipv4.tcp_tw_reuse = 1

# TCP Max Syn Backlog
net.ipv4.tcp_max_syn_backlog = 4096

# TCP Slow Start After Idle
net.ipv4.tcp_slow_start_after_idle = 0

# ARP Cache Settings
net.ipv4.neigh.default.gc_thresh1 = 1024
net.ipv4.neigh.default.gc_thresh2 = 2048
net.ipv4.neigh.default.gc_thresh3 = 4096

# Buffer Overflow Protection
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.netdev_max_backlog = 5000

# Shared Memory
kernel.shmmax = 68719476736
kernel.shmall = 4294967296

# File Handles
fs.file-max = 2097152

# Exec Shield (kernel.randomize_va_space = 2)
kernel.randomize_va_space = 2

# Core Dumps
kernel.core_pattern = |/bin/false
fs.suid_dumpable = 0

# ExecShield protection
kernel.exec-shield = 2

# Kernel PID Hardening
kernel.pid_max = 65536

# Prevent Kernel Pointer Leaks
kernel.kptr_restrict = 2

# Restrict dmesg
kernel.dmesg_restrict = 1

# Disable kexec system call
kernel.kexec_load_disabled = 1

# Disable AppArmor features (if using AppArmor)
# kernel.apparmor_restrict_unprivileged_userns = 1

# Harden BPF
kernel.unprivileged_bpf_disabled = 1

# Disable user namespaces (optional, may break some containers)
# kernel.unprivileged_userns_clone = 0

# Restrict loading TTY line disciplines
dev.tty.ldisc_autoload = 0

# Restrict perf_event_open access
kernel.perf_event_paranoid = 3

# Disable ftrace debugging
kernel.ftrace_enabled = 0

# Prevent power management attacks
kernel.modules_disabled = 0  # Don't set to 1 unless you never load modules

# Address Space Layout Randomization (ASLR)
kernel.randomize_va_space = 2

# Disable magic-sysrq key
kernel.sysrq = 0

# Restrict /proc and /sys access
filesystem.protected_regular = 1
filesystem.protected_fifos = 2

# Network Stack Hardening
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_adv_win_scale = 2

# IPv6 Hardening
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0
net.ipv6.conf.all.autoconf = 0
net.ipv6.conf.default.autoconf = 0

# Reduce UDP timeouts
net.ipv4.udp_mem = 65536 131072 262144

# Reduce TCP timeouts
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 5

# Prevent SYN flood
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Mitigate TCP time-wait assassination hazards
net.ipv4.tcp_rfc1337 = 1

# TCP Fast Open
net.ipv4.tcp_fastopen = 3

# TCP Small Queues
net.ipv4.tcp_small_queues = 1

EOF

    # Apply sysctl settings
    sysctl -p "$sysctl_conf"

    log_success "Kernel parameters hardened"
}

################################################################################
# System Hardening
################################################################################

harden_system() {
    log_info "Applying system hardening..."

    # Disable unnecessary services
    log_info "Disabling unnecessary services..."

    # List of services to disable
    SERVICES_TO_DISABLE=(
        "avahi-daemon"
        "cups"
        "dns-clean"
        "exim4"
        "saned"
        "spamd"
        "bluetooth"
        "hidd"
        "pand"
        "dund"
    )

    for service in "${SERVICES_TO_DISABLE[@]}"; do
        if systemctl is-active --quiet "$service" 2>/dev/null; then
            systemctl stop "$service"
            systemctl disable "$service"
            log_success "Disabled $service"
        fi
    done

    # Secure /tmp
    if ! grep -q "/tmp" /etc/fstab; then
        log_warning "Consider creating separate partition for /tmp with noexec,nodev,nosuid"
    fi

    # Disable core dumps
    cat > /etc/security/limits.d/50-security.conf << 'EOF'
* hard core 0
* soft core 0
EOF

    # Restrict access to compilation tools
    if [[ -f /usr/bin/gcc ]]; then
        chmod 750 /usr/bin/gcc
        chown root:compiler-users /usr/bin/gcc 2>/dev/null || true
    fi

    # Secure cron
    touch /etc/cron.allow
    chmod 600 /etc/cron.allow
    rm -f /etc/cron.deny

    # Restrict at
    touch /etc/at.allow
    chmod 600 /etc/at.allow
    rm -f /etc/at.deny

    log_success "System hardening applied"
}

################################################################################
# Password Policy
################################################################################

configure_password_policy() {
    log_info "Configuring password policy..."

    # Configure PAM password quality
    cat > /etc/security/pwquality.conf << 'EOF'
# Password Quality Controls
minlen = 14
minclass = 3
maxrepeat = 3
dcredit = -1
ucredit = -1
lcredit = -1
ocredit = -1
difok = 3
enforce_for_root
EOF

    # Configure login defs
    backup_file "/etc/login.defs"

    sed -i 's/^PASS_MAX_DAYS.*/PASS_MAX_DAYS 90/' /etc/login.defs
    sed -i 's/^PASS_MIN_DAYS.*/PASS_MIN_DAYS 1/' /etc/login.defs
    sed -i 's/^PASS_WARN_AGE.*/PASS_WARN_AGE 7/' /etc/login.defs
    sed -i 's/^LOGIN_RETRIES.*/LOGIN_RETRIES 3/' /etc/login.defs
    sed -i 's/^LOGIN_TIMEOUT.*/LOGIN_TIMEOUT 60/' /etc/login.defs

    # Configure password aging
    cat >> /etc/pam.d/common-password << 'EOF'
# Password hashing algorithm
password [success=1 default=ignore] pam_unix.so obscure sha512 shadow yescrypt
EOF

    log_success "Password policy configured"
}

################################################################################
# Log Monitoring Setup
################################################################################

configure_logging() {
    log_info "Configuring system logging..."

    # Configure rsyslog
    cat > /etc/rsyslog.d/50-security.conf << 'EOF'
# Security logging configuration

# Log auth messages to auth.log
auth,authpriv.*                 /var/log/auth.log

# Log kernel messages
kern.*                          /var/log/kern.log

# Log all mail messages
mail.*                          -/var/log/mail.log

# Log cron jobs
cron.*                          /var/log/cron.log

# Log all user messages
*.=info;*.=notice;*.=warn;\
    auth,authpriv.none;\
    cron,daemon.none;\
    mail,news.none              -/var/log/messages

# Emergency messages to all users
*.emerg                         :omusrmsg:*

# Store boot messages
kern.*                          ~/boot.log

# Remote logging (optional, configure server IP)
# *.* @@logserver.example.com:514
EOF

    # Restart rsyslog
    systemctl restart rsyslog

    # Configure logrotate
    cat > /etc/logrotate.d/security << 'EOF'
/var/log/auth.log
/var/log/kern.log
/varlog/syslog
{
    daily
    missingok
    rotate 90
    compress
    delaycompress
    notifempty
    create 0640 syslog adm
    sharedscripts
    postrotate
        systemctl reload rsyslog >/dev/null 2>&1 || true
    endscript
}
EOF

    log_success "Logging configured"
}

################################################################################
# Automatic Updates
################################################################################

configure_unattended_upgrades() {
    log_info "Configuring automatic security updates..."

    cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

# Automatically reboot WITHOUT confirmation if a reboot is required
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-Time "02:00";

# Remove unused dependencies after upgrade
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";

# Auto clean
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::InstallOnShutdown "false";
Unattended-Upgrade::Verbose "true";
Unattended-Upgrade::Debug "false";

# Send email
Unattended-Upgrade::Mail "security@yourdomain.com";
Unattended-Upgrade::MailOnlyOnError "true";
EOF

    # Enable automatic updates
    dpkg-reconfigure --priority=low unattended-upgrades

    log_success "Automatic updates configured"
}

################################################################################
# Audit Configuration
################################################################################

configure_auditd() {
    log_info "Configuring audit daemon..."

    # Create audit rules
    cat > /etc/audit/rules.d/audit.rules << 'EOF'
# Delete all existing rules
-D

# Set buffer size
-b 8192

# Monitor for file deletions
-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete
-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete

# Monitor for privileged commands
-a always,exit -F path=/bin/su -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged_cmds
-a always,exit -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged_cmds
-a always,exit -F path=/bin/ping -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged_cmds

# Monitor for system changes
-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mount
-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mount

# Monitor for file access
-w /etc/passwd -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/sudoers -p wa -k identity

# Monitor for network changes
-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale
-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale

# Monitor for SSH configuration changes
-w /etc/ssh/sshd_config -p wa -k sshd-config

# Monitor for cron changes
-w /etc/crontab -p wa -k cron
-w /etc/cron.d -p wa -k cron
-w /etc/cron.daily -p wa -k cron
-w /etc/cron.hourly -p wa -k cron
-w /etc/cron.weekly -p wa -k cron

# Make the configuration immutable
-e 2
EOF

    # Restart auditd
    systemctl enable auditd
    systemctl restart auditd

    log_success "Audit daemon configured"
}

################################################################################
# Security Scanning Setup
################################################################################

setup_security_scanning() {
    log_info "Setting up security scanning..."

    # Create cron jobs for security scans

    # Daily rootkit check
    cat > /etc/cron.daily/security-rootkit-check << 'EOF'
#!/bin/bash
# Daily rootkit scan
/usr/bin/rkhunter --cronjob --report-warnings-only
/usr/sbin/chkrootkit > /var/log/chkrootkit.log 2>&1
EOF
    chmod +x /etc/cron.daily/security-rootkit-check

    # Weekly security audit
    cat > /etc/cron.weekly/security-audit << 'EOF'
#!/bin/bash
# Weekly comprehensive security audit
DATE=$(date +%Y%m%d)
REPORT_DIR="/var/log/security-audits"
mkdir -p "$REPORT_DIR"

# Run Lynis
/usr/bin/lynis audit system --quick --report-file "$REPORT_DIR/lynis-report-$DATE.txt"

# Run security scan report
cat > "$REPORT_DIR/security-summary-$DATE.txt" << EOR
================================================================================
                    Security Audit Report - $(date)
================================================================================

================================================================================
Disk Usage:
================================================================================
df -h

================================================================================
Open Ports:
================================================================================
ss -tulpn

================================================================================
Running Processes:
================================================================================
ps aux --sort=-%mem | head -20

================================================================================
Failed Login Attempts:
================================================================================
grep "Failed password" /var/log/auth.log | tail -20

================================================================================
Last 20 Logins:
================================================================================
lastlog -u 1000-60000 | head -20

================================================================================
Security Updates Available:
================================================================================
apt list --upgradable 2>/dev/null | grep -i security

================================================================================
End of Report
================================================================================
EOR

# Email report (if configured)
# mail -s "Security Audit Report - $(hostname)" security@yourdomain.com < "$REPORT_DIR/security-summary-$DATE.txt"
EOF
    chmod +x /etc/cron.weekly/security-audit

    log_success "Security scanning configured"
}

################################################################################
# Finalize
################################################################################

create_security_summary() {
    log_info "Creating security summary..."

    local summary_file="/root/security-hardening-summary-$(date +%Y%m%d).txt"

    cat > "$summary_file" << EOF
================================================================================
              SERVER HARDING COMPLETION SUMMARY
================================================================================

Server: $(hostname)
Date: $(date)
IP Address: $(hostname -I | awk '{print $1}')
Log File: $LOG_FILE

================================================================================
CHANGES APPLIED:
================================================================================

✓ Security tools installed (fail2ban, ufw, auditd, etc.)
✓ SSH hardened (key-based auth, custom port, secure ciphers)
✓ Firewall configured (UFW with restrictive rules)
✓ Fail2Ban configured (SSH, HTTP protections)
✓ Kernel parameters hardened (sysctl)
✓ Password policy configured (14 char min, complexity)
✓ System hardening applied (services disabled)
✓ Logging configured (rsyslog, logrotate)
✓ Automatic updates enabled (unattended-upgrades)
✓ Audit daemon configured (file access monitoring)
✓ Security scanning scheduled (daily/weekly)

================================================================================
CRITICAL CONFIGURATION CHANGES:
================================================================================

1. SSH Port: 2222 (was 22) - UPDATE YOUR SSH CLIENTS!
2. Root login: DISABLED
3. Password auth: DISABLED (key-based only)
4. Firewall: ENABLED (only HTTP, HTTPS, SSH allowed)

================================================================================
IMMEDIATE ACTIONS REQUIRED:
================================================================================

1. Add your SSH public key to ~/.ssh/authorized_keys
2. Test SSH login on new port: ssh -p 2222 user@server
3. Update firewall rules if needed: sudo ufw allow PORT
4. Configure email for alerts: /etc/fail2ban/jail.local
5. Review and update AllowedUsers in /etc/ssh/sshd_config
6. Schedule first backup

================================================================================
SECURITY REMINDERS:
================================================================================

- Server is now hardened but NOT invincible
- Apply security updates promptly
- Monitor logs regularly: tail -f /var/log/auth.log
- Review Fail2Ban status: fail2ban-client status
- Run weekly security audits
- Keep backups off-site
- Use strong SSH passphrases
- Rotate keys quarterly
- Document all changes
- Plan incident response

================================================================================
NEXT STEPS:
================================================================================

1. Setup automated backups
2. Configure monitoring (Prometheus/Grafana, Datadog, etc.)
3. Setup log aggregation (ELK, Splunk, etc.)
4. Implement SIEM (Security Information and Event Management)
5. Schedule quarterly security audits
6. Penetration testing
7. Security training for team
8. Document incident response procedures

================================================================================
SECURITY TOOLS INSTALLED:
================================================================================

- fail2ban: Intrusion prevention
- ufw: Firewall management
- auditd: File access monitoring
- rkhunter: Rootkit detection
- chkrootkit: Rootkit detection
- lynis: Security auditing
- aide: File integrity monitoring
- unattended-upgrades: Automatic security updates

================================================================================
IMPORTANT FILES:
================================================================================

- SSH config: /etc/ssh/sshd_config
- Firewall: sudo ufw status
- Fail2Ban: /etc/fail2ban/jail.local
- Sysctl: /etc/sysctl.d/99-security-hardening.conf
- Audit rules: /etc/audit/rules.d/audit.rules
- Logs: /var/log/auth.log, /var/log/syslog

================================================================================
BACKUPS CREATED:
================================================================================
EOF

    find /root/backups/hardening_* -type f 2>/dev/null >> "$summary_file"

    cat >> "$summary_file" << EOF

================================================================================
END OF SUMMARY
================================================================================

Generated by: harden-ubuntu-server.sh
For support: security@yourdomain.com

================================================================================

WARNING: THIS IS AUTOMATED HARDENING. MANUAL REVIEW STILL REQUIRED!

================================================================================
EOF

    cat "$summary_file"
    log_success "Security summary created: $summary_file"
}

################################################################################
# MAIN EXECUTION
################################################################################

main() {
    log_info "Starting Ubuntu server hardening..."
    log_info "Log file: $LOG_FILE"

    check_root

    # Prompt for confirmation
    echo ""
    log_warning "This script will make significant changes to your server!"
    log_warning "Ensure you have:"
    log_warning "  - Root access"
    log_warning "  - SSH key access (password auth will be disabled)"
    log_warning "  - Backup of important data"
    log_warning "  - Access to console (in case of SSH issues)"
    echo ""
    read -p "Continue? (yes/no): " confirm

    if [[ "$confirm" != "yes" ]]; then
        log_info "Aborted by user"
        exit 0
    fi

    # Create backup directory
    mkdir -p /root/backups

    # Execute hardening functions
    install_security_tools
    harden_ssh
    configure_firewall
    configure_fail2ban
    harden_kernel
    harden_system
    configure_password_policy
    configure_logging
    configure_unattended_upgrades
    configure_auditd
    setup_security_scanning
    create_security_summary

    echo ""
    log_success "═══════════════════════════════════════════════════════════"
    log_success "       SERVER HARDENING COMPLETE!"
    log_success "═══════════════════════════════════════════════════════════"
    echo ""
    log_warning "IMPORTANT: Test SSH access on new port (2222) BEFORE logging out!"
    log_warning "Open a new terminal and test: ssh -p 2222 user@server"
    echo ""
    log_info "Log file: $LOG_FILE"
    log_info "Summary: /root/security-hardening-summary-$(date +%Y%m%d).txt"
    echo ""
}

# Run main function
main "$@"
