#!/bin/bash
# Secure DNS Configuration Script
# Configures secure DNS settings on the system

set -e

echo "🔐 SECURING DNS CONFIGURATION"
echo "============================="

# Check if running as root for system-wide changes
if [ "$EUID" -ne 0 ]; then
    echo "⚠️  Some system-wide changes require sudo privileges"
    echo "   You may be prompted for your password"
fi

# Backup current DNS configuration
echo "📋 Backing up current DNS configuration..."

# Backup resolv.conf
if [ -f /etc/resolv.conf ]; then
    sudo cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)
    echo "✅ Backed up /etc/resolv.conf"
fi

# Configure secure DNS resolvers
echo "🔧 Configuring secure DNS resolvers..."

# Cloudflare and Google DNS (with DNSSEC)
SECURE_DNS=(
    "nameserver 1.1.1.1"
    "nameserver 1.0.0.1"
    "nameserver 8.8.8.8"
    "nameserver 8.8.4.4"
    "options timeout:2"
    "options attempts:3"
    "options rotate"
)

# Create new resolv.conf
echo "Creating new /etc/resolv.conf with secure DNS resolvers..."

{
    echo "# Generated by PsychSync DNS Security Configuration"
    echo "# Secure DNS resolvers with DNSSEC support"
    echo "# Generated: $(date)"
    echo ""
    for dns_entry in "${SECURE_DNS[@]}"; do
        echo "$dns_entry"
    done
    echo ""
    echo "# Enable DNSSEC validation"
    echo "options edns0"
    echo "options trust-ad"
} | sudo tee /etc/resolv.conf.new

# Apply new configuration
sudo mv /etc/resolv.conf.new /etc/resolv.conf
echo "✅ Updated /etc/resolv.conf with secure DNS resolvers"

# Configure NetworkManager (if available) to use secure DNS
if command -v nmcli >/dev/null 2>&1; then
    echo "🔧 Configuring NetworkManager DNS settings..."

    # Get active connections
    ACTIVE_CONNECTIONS=$(nmcli -t -f NAME,TYPE connection show --active | grep ethernet | cut -d: -f1)

    for connection in $ACTIVE_CONNECTIONS; do
        echo "   Configuring connection: $connection"

        # Set DNS servers
        nmcli connection modify "$connection" ipv4.dns "1.1.1.1 8.8.8.8" ipv4.ignore-auto-dns yes

        # Set DNSSEC validation
        nmcli connection modify "$connection" ipv4.dnssec yes

        # Apply changes
        nmcli connection up "$connection" >/dev/null 2>&1 || true

        echo "   ✅ Updated $connection"
    done
fi

# Configure systemd-resolved (if available)
if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    echo "🔧 Configuring systemd-resolved with secure DNS..."

    # Create resolved.conf configuration
    sudo mkdir -p /etc/systemd/resolved.conf.d

    {
        echo "[Resolve]"
        echo "# PsychSync Secure DNS Configuration"
        echo "DNS=1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4"
        echo "# FallbackDNS=9.9.9.9 149.112.112.112"
        echo "DNSSEC=yes"
        echo "DNSOverTLS=yes"
        echo "Cache=yes"
        echo "DNSStubListener=no"
    } | sudo tee /etc/systemd/resolved.conf.d/psychsync-dns.conf

    # Restart systemd-resolved
    sudo systemctl restart systemd-resolved

    # Update resolv.conf symlink
    if [ -L /etc/resolv.conf ]; then
        sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
    fi

    echo "✅ Configured systemd-resolved with DNSSEC"
fi

# Configure dnsmasq (if available)
if command -v dnsmasq >/dev/null 2>&1; then
    echo "🔧 Configuring dnsmasq with secure DNS..."

    # Create dnsmasq configuration
    {
        echo "# PsychSync Secure DNS Configuration"
        echo "# Generated: $(date)"
        echo ""
        echo "server=1.1.1.1"
        echo "server=1.0.0.1"
        echo "server=8.8.8.8"
        echo "server=8.8.4.4"
        echo "all-servers"
        echo "cache-size=1000"
        echo "dnssec"
        echo "trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D"
    } | sudo tee /etc/dnsmasq.d/psychsync-secure-dns.conf

    # Restart dnsmasq
    sudo systemctl restart dnsmasq 2>/dev/null || sudo service dnsmasq restart 2>/dev/null || true

    echo "✅ Configured dnsmasq with secure DNS"
fi

# Test DNS configuration
echo "🧪 Testing DNS configuration..."

# Test basic resolution
echo "   Testing basic DNS resolution..."
if nslookup google.com >/dev/null 2>&1; then
    echo "   ✅ Basic DNS resolution working"
else
    echo "   ❌ Basic DNS resolution failed"
    exit 1
fi

# Test DNSSEC validation
echo "   Testing DNSSEC validation..."
if command -v dig >/dev/null 2>&1; then
    if dig +dnssec DNSKEY google.com >/dev/null 2>&1; then
        echo "   ✅ DNSSEC validation available"
    else
        echo "   ⚠️  DNSSEC validation may not be working"
    fi
else
    echo "   ℹ️  dig command not available, skipping DNSSEC test"
fi

# Test secure resolvers
echo "   Testing secure DNS resolvers..."
for resolver in "1.1.1.1" "8.8.8.8"; do
    if nslookup google.com $resolver >/dev/null 2>&1; then
        echo "   ✅ Resolver $resolver responding"
    else
        echo "   ❌ Resolver $resolver not responding"
    fi
done

# Create environment file for Python DNS configuration
echo "🔧 Creating Python DNS configuration..."
cat > .dns_secure << 'EOF'
# PsychSync Secure DNS Configuration
# These variables will be used by the Python DNS security module

export DNSSEC_ENABLED=true
export SECURE_DNS_RESOLVERS="1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4"
export DNS_TIMEOUT=2.0
export DNS_CACHE_TTL=300
export DNS_VALIDATION_ENABLED=true
EOF

echo "✅ Created .dns_secure environment file"

# Create monitoring script for DNS health
echo "🔧 Creating DNS health monitoring script..."
cat > scripts/monitor_dns_health.sh << 'EOF'
#!/bin/bash
# DNS Health Monitoring Script

DNS_RESOLVERS=("1.1.1.1" "8.8.8.8" "1.0.0.1" "8.8.4.4")
LOG_FILE="logs/dns_health.log"
ALERT_THRESHOLD=2  # Alert if more than 2 resolvers fail

mkdir -p logs

timestamp() {
    date '+%Y-%m-%d %H:%M:%S'
}

failed_count=0

echo "$(timestamp): Starting DNS health check" >> $LOG_FILE

for resolver in "${DNS_RESOLVERS[@]}"; do
    if nslookup google.com $resolver >/dev/null 2>&1; then
        echo "$(timestamp): ✅ Resolver $resolver is healthy" >> $LOG_FILE
    else
        echo "$(timestamp): ❌ Resolver $resolver failed" >> $LOG_FILE
        ((failed_count++))
    fi
done

if [ $failed_count -ge $ALERT_THRESHOLD ]; then
    echo "$(timestamp): 🚨 DNS HEALTH ALERT: $failed_count resolvers failed!" >> $LOG_FILE
    # Here you could add email/SMS alerts
fi

echo "$(timestamp): DNS health check completed" >> $LOG_FILE
echo "" >> $LOG_FILE
EOF

chmod +x scripts/monitor_dns_health.sh
echo "✅ Created DNS health monitoring script"

echo ""
echo "🎉 DNS SECURITY CONFIGURATION COMPLETED"
echo "======================================"
echo ""
echo "✅ Configured secure DNS resolvers:"
echo "   - Cloudflare DNS (1.1.1.1, 1.0.0.1)"
echo "   - Google DNS (8.8.8.8, 8.8.4.4)"
echo ""
echo "✅ Enabled DNSSEC validation"
echo "✅ Configured DNS caching"
echo "✅ Created monitoring scripts"
echo ""
echo "📋 Next Steps:"
echo "1. Test your applications to ensure they work with the new DNS settings"
echo "2. Set up the DNS health monitoring script in a cron job:"
echo "   */5 * * * * /path/to/psychsync/scripts/monitor_dns_health.sh"
echo "3. Monitor the DNS security endpoints in your PsychSync application"
echo ""
echo "🔒 Your system is now configured with secure DNS!"
