#!/usr/bin/env python3
"""
Simple Test Suite Generator

A working version of the test generator that creates comprehensive test suites
for Python modules using AST analysis.

Usage:
    python scripts/simple_test_generator.py --module app.services.user_service
"""

import argparse
import ast
import os
import sys
from datetime import datetime
from pathlib import Path

# Add project root to Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))


def analyze_module(module_path: str) -> dict:
    """Analyze a Python module and extract functions/classes"""

    with open(module_path, "r", encoding="utf-8") as f:
        content = f.read()

    try:
        tree = ast.parse(content)
    except SyntaxError as e:
        raise ValueError(f"Invalid Python syntax in {module_path}: {e}")

    functions = []
    classes = []

    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            functions.append(
                {
                    "name": node.name,
                    "is_async": isinstance(node, ast.AsyncFunctionDef),
                    "docstring": ast.get_docstring(node),
                    "line_number": node.lineno,
                }
            )
        elif isinstance(node, ast.ClassDef):
            methods = []
            for item in node.body:
                if isinstance(item, ast.FunctionDef):
                    methods.append(
                        {
                            "name": item.name,
                            "is_async": isinstance(item, ast.AsyncFunctionDef),
                            "docstring": ast.get_docstring(item),
                            "line_number": item.lineno,
                        }
                    )

            classes.append(
                {
                    "name": node.name,
                    "methods": methods,
                    "docstring": ast.get_docstring(node),
                }
            )

    return {
        "functions": functions,
        "classes": classes,
        "module_name": Path(module_path).stem,
    }


def generate_test_file(module_info: dict) -> str:
    """Generate comprehensive test file content"""

    module_name = module_info["module_name"]
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    test_content = f'''"""
Comprehensive Test Suite for {module_name}

Auto-generated on: {timestamp}
Test Coverage Target: >80%
Test Types: Unit (70%), Integration (20%), Security (10%)

Generated by: scripts/simple_test_generator.py
"""

import pytest
import asyncio
from unittest.mock import Mock, AsyncMock, patch
from fastapi.testclient import TestClient
from httpx import AsyncClient
from datetime import datetime, timedelta

# Project imports
from app.main import app
from app.core.config import settings
from app.core.database import get_async_session
from sqlalchemy.ext.asyncio import AsyncSession


@pytest.fixture
async def async_client():
    """Async test client"""
    async with AsyncClient(app=app, base_url="http://test") as client:
        yield client


@pytest.fixture
async def test_session():
    """Test database session"""
    async for session in get_async_session():
        yield session


@pytest.fixture
def mock_user():
    """Mock user for testing"""
    return {{
        "id": 1,
        "email": "test@example.com",
        "full_name": "Test User",
        "is_active": True,
        "is_superuser": False
    }}


@pytest.fixture
def mock_token():
    """Mock JWT token"""
    from app.services.security import create_access_token
    return create_access_token(data={{"sub": "test@example.com"}})


'''

    # Generate tests for standalone functions
    if module_info["functions"]:
        test_content += "\n\nclass TestModuleFunctions:\n"
        for func in module_info["functions"]:
            if not func["name"].startswith("_"):
                test_content += generate_function_test(func, is_method=False)

    # Generate tests for class methods
    for cls in module_info["classes"]:
        test_content += f'\n\nclass Test{cls["name"]}:\n'
        test_content += f'    """Tests for {cls["name"]} class"""\n\n'

        for method in cls["methods"]:
            if not method["name"].startswith("_"):
                test_content += generate_function_test(
                    method, is_method=True, class_name=cls["name"]
                )

    # Add integration tests
    test_content += generate_integration_tests()

    # Add security tests
    test_content += generate_security_tests()

    # Add performance tests
    test_content += generate_performance_tests()

    # Add coverage info
    test_content += '''

# Coverage Information
# This test suite aims for >80% code coverage
# Run coverage with: pytest --cov=MODULE_NAME --cov-report=html

def test_coverage_summary():
    """Coverage summary test"""
    assert True  # Placeholder for coverage validation


if __name__ == "__main__":
    import subprocess
    print("Running comprehensive test suite...")
    subprocess.run([
        sys.executable, "-m", "pytest",
        __file__,
        "--cov=.",
        "--cov-report=html",
        "--cov-report=term-missing",
        "-v"
    ])
'''

    return test_content


def generate_function_test(
    func: dict, is_method: bool = False, class_name: str = None
) -> str:
    """Generate test for a specific function"""

    func_name = func["name"]
    prefix = f"test_{class_name.lower()}_" if class_name else "test_"
    test_name = f"{prefix}{func_name}"

    # Determine test patterns based on function name
    test_scenarios = []

    if "create" in func_name.lower():
        test_scenarios = ["valid_creation", "invalid_creation", "duplicate_creation"]
    elif "get" in func_name.lower() or "find" in func_name.lower():
        test_scenarios = ["found_existing", "not_found", "invalid_id"]
    elif "update" in func_name.lower():
        test_scenarios = ["valid_update", "invalid_update", "not_found"]
    elif "delete" in func_name.lower() or "remove" in func_name.lower():
        test_scenarios = ["existing_deletion", "not_found_deletion"]
    elif "auth" in func_name.lower() or "login" in func_name.lower():
        test_scenarios = ["valid_credentials", "invalid_credentials", "account_locked"]
    else:
        test_scenarios = ["happy_path", "error_case", "edge_case"]

    test_content = f"    def {test_name}(self"

    # Add common parameters for test methods
    test_content += ", mock_db=None, mock_user=None):\n"
    test_content += f'        """Test {func_name} function"""\n\n'

    for i, scenario in enumerate(test_scenarios):
        test_content += f'        # Test {scenario.replace("_", " ").title()}\n'
        test_content += "        try:\n"

        if is_method and class_name:
            test_content += f"            # Setup mock instance\n"
            test_content += f"            instance = {class_name}()\n"

        # Add scenario-specific setup
        if "valid" in scenario or "found" in scenario or "happy" in scenario:
            test_content += "            # Arrange: Valid test data\n"
            test_content += '            test_data = {"key": "value"}\n'
        elif "invalid" in scenario or "error" in scenario:
            test_content += "            # Arrange: Invalid test data\n"
            test_content += '            test_data = {"invalid": "data"}\n'
        elif "not_found" in scenario:
            test_content += "            # Arrange: Non-existent resource\n"
            test_content += "            test_id = 999999\n"

        # Add execution step
        test_content += "            \n"
        test_content += "            # Act\n"

        if is_method and class_name:
            test_content += f"            result = instance.{func_name}("
        else:
            test_content += f"            result = {func_name}("

        # Add parameters based on function name hints
        if "id" in func_name.lower():
            test_content += 'test_id if "test_id" in locals() else 1'
        elif "data" in func_name.lower():
            test_content += 'test_data if "test_data" in locals() else {"key": "value"}'
        else:
            test_content += "mock_db or test_data"

        test_content += ")\n\n"

        # Add assertion step
        test_content += "            # Assert\n"
        if "invalid" in scenario or "error" in scenario:
            test_content += "            # Should handle error gracefully\n"
            test_content += (
                "            assert True  # Implement specific error assertions\n"
            )
        else:
            test_content += "            assert result is not None\n"
            test_content += (
                "            # Add specific assertions for expected behavior\n"
            )

        test_content += "\n        except Exception as e:\n"
        test_content += f'            if "{scenario}" == "error_case":\n'
        test_content += "                # Expected error for error case\n"
        test_content += "                pass\n"
        test_content += "            else:\n"
        test_content += (
            '                pytest.fail(f"Unexpected error in {scenario}: {{e}}")\n'
        )

        if i < len(test_scenarios) - 1:
            test_content += "\n"

    test_content += "\n"
    return test_content


def generate_integration_tests() -> str:
    """Generate integration test section"""
    return '''
@pytest.mark.integration
class TestIntegration:
    """Integration tests for module"""

    @pytest.mark.asyncio
    async def test_database_integration(self, test_session: AsyncSession):
        """Test database integration"""
        # Test database operations
        assert test_session is not None
        # Add specific database tests based on module functionality

    @pytest.mark.asyncio
    async def test_api_integration(self, async_client: AsyncClient):
        """Test API integration"""
        # Test API endpoints
        response = await async_client.get("/")
        assert response.status_code in [200, 404]  # 404 if no root endpoint
        # Add specific API endpoint tests

    def test_service_integration(self):
        """Test service layer integration"""
        # Test service coordination
        assert True  # Implement specific service integration tests
'''


def generate_security_tests() -> str:
    """Generate security test section"""
    return '''
@pytest.mark.security
class TestSecurity:
    """Security tests for module"""

    def test_input_validation(self):
        """Test input validation security"""
        # Test against injection attacks
        malicious_inputs = [
            "'; DROP TABLE users; --",
            "<script>alert('XSS')</script>",
            "../../../etc/passwd"
        ]

        for payload in malicious_inputs:
            # Test that malicious inputs are handled safely
            # Add specific security assertions
            assert True  # Implement specific security tests

    def test_authentication_security(self):
        """Test authentication security"""
        # Test password security, token validation, etc.
        # Add authentication-specific security tests
        assert True

    def test_authorization_security(self):
        """Test authorization security"""
        # Test access controls and permissions
        # Add authorization-specific security tests
        assert True
'''


def generate_performance_tests() -> str:
    """Generate performance test section"""
    return '''
@pytest.mark.performance
class TestPerformance:
    """Performance tests for module"""

    def test_response_time(self):
        """Test response time performance"""
        import time

        start_time = time.time()
        # Execute typical operation
        # Add actual function call here
        duration = time.time() - start_time

        # Should complete within reasonable time
        assert duration < 1.0  # 1 second limit

    @pytest.mark.asyncio
    async def test_concurrent_requests(self):
        """Test concurrent request handling"""
        import asyncio

        async def make_request():
            # Simulate concurrent request
            await asyncio.sleep(0.01)  # Simulate processing
            return "success"

        # Test multiple concurrent requests
        tasks = [make_request() for _ in range(10)]
        results = await asyncio.gather(*tasks)

        assert all(r == "success" for r in results)
        assert len(results) == 10
'''


def main():
    """Main CLI interface"""
    parser = argparse.ArgumentParser(
        description="Generate comprehensive test suites for Python modules",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/simple_test_generator.py --module app.services.user_service
    python scripts/simple_test_generator.py --module app.api.v1.endpoints.users
        """,
    )

    parser.add_argument(
        "--module",
        "-m",
        type=str,
        required=True,
        help="Module path to generate tests for (e.g., app.services.user_service)",
    )

    parser.add_argument(
        "--output",
        "-o",
        type=str,
        help="Output file path (optional, defaults to tests/module_name_test.py)",
    )

    args = parser.parse_args()

    try:
        # Determine module file path
        module_path = project_root / f"{args.module.replace('.', '/')}.py"

        if not module_path.exists():
            print(f"❌ Module file not found: {module_path}")
            sys.exit(1)

        print(f"🔍 Analyzing module: {args.module}")
        module_info = analyze_module(str(module_path))

        print(
            f"📝 Found {len(module_info['functions'])} functions and {len(module_info['classes'])} classes"
        )

        # Generate test suite
        print("🚀 Generating comprehensive test suite...")
        test_content = generate_test_file(module_info)

        # Determine output path
        if args.output:
            output_path = project_root / args.output
        else:
            test_file_name = f"{args.module.replace('.', '_')}_test.py"
            output_path = project_root / "tests" / test_file_name

        # Create directories if needed
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Write test file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(test_content)

        print(f"✅ Test suite generated successfully!")
        print(f"📁 Saved to: {output_path}")
        print(f"🎯 Next steps:")
        print(f"   1. Review and customize generated tests")
        print(f"   2. Run: pytest {output_path.relative_to(project_root)} -v")
        print(
            f"   3. Check coverage: pytest --cov={args.module} --cov-report=term-missing"
        )

    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
