"""
AI Agents for PsychSync
Autonomous agents for code quality, testing, security, and monitoring
"""

from .agent_framework import (
    AgentConfig,
    AgentOrchestrator,
    AgentResult,
    AgentStatus,
    BaseAgent,
    Priority,
    analyze_code_complexity,
    find_files,
    read_file,
    run_command,
)

# Analytics & Workflow Agents
from .analytics_workflow_agents import (
    APITestingAgent,
    BackupAgent,
    CIPipelineMonitorAgent,
    CodeReviewAgent,
    DependencyUpdaterAgent,
    DeploymentSafetyAgent,
    DocumentationAuditorAgent,
    ErrorRateMonitorAgent,
    HealthMonitorAgent,
    IncidentResponseAgent,
    LintEnforcerAgent,
    LoadTestingAgent,
    MergeSafetyAgent,
    PerformanceMetricsAgent,
    ReleaseValidatorAgent,
    ScalabilityAnalyzerAgent,
    SecurityScannerAgent,
    SLAMonitorAgent,
    TestCoverageAgent,
    TestDataGeneratorAgent,
    TypeCheckValidatorAgent,
    UITestingAgent,
    UsageStatisticsAgent,
    UserBehaviorAnalyticsAgent,
)

# Code Quality Agents
from .code_quality_agents import (
    APIDriftDetectorAgent,
    AutoTestGeneratorAgent,
    BugSummarizerAgent,
    CodeQualityMonitorAgent,
    CodeStandardizerAgent,
    DocumentationCompletenessAgent,
    DuplicateIssueDetectorAgent,
    EngineeringPerformanceAgent,
    JSONSchemaValidatorAgent,
    LogAnomalyScannerAgent,
    ModuleDecomposerAgent,
    PRQualityScorerAgent,
    UnusedCodeDetectorAgent,
)

# Specialized Agents
from .specialized_agents import (
    ArchitectureDriftDetectorAgent,
    BugEnvironmentCreatorAgent,
    CodingStyleEnforcerAgent,
)
from .specialized_agents import DependencyUpdaterAgent as DependencyUpdaterAgentV2
from .specialized_agents import (
    EncryptionStrategyAgent,
    EnvironmentConfigDetectorAgent,
    IncidentMitigationPlannerAgent,
    LocalizationGapDetectorAgent,
    PerformanceRegressionAgent,
    PermissionGapDetectorAgent,
    PRToJiraMapperAgent,
    RefactoringTargetProposerAgent,
    ReleaseNotesGeneratorAgent,
    SecurityHeaderValidatorAgent,
    SlowEndpointTrackerAgent,
    TestCoverageReporterAgent,
    ThirdPartyScriptSafetyAgent,
    UptimeMonitorAgent,
    UXFrictionTrackerAgent,
    WeeklyStabilityScorerAgent,
)

# Testing & Performance Agents
from .testing_performance_agents import (
    AccessibilityAuditorAgent,
    APIMockGeneratorAgent,
    BreakingChangeDetectorAgent,
    BuildFailureAnalyzerAgent,
    BundleOptimizerAgent,
    CachingConfigOptimizerAgent,
    CommentImproverAgent,
    DebugCodeRemoverAgent,
    DeprecatedLibraryDetectorAgent,
    ErrorCodeGeneratorAgent,
    MemoryLeakDetectorAgent,
    PaginationValidatorAgent,
    QueryOptimizerAgent,
    ReRenderOptimizerAgent,
    SpaghettiCodeRefactorAgent,
    SQLInjectionAuditorAgent,
    UnusedCSSDetectorAgent,
)

__all__ = [
    # Framework
    "BaseAgent",
    "AgentConfig",
    "AgentResult",
    "AgentOrchestrator",
    "AgentStatus",
    "Priority",
    "run_command",
    "find_files",
    "read_file",
    "analyze_code_complexity",
    # Code Quality Agents (13)
    "CodeQualityMonitorAgent",
    "BugSummarizerAgent",
    "EngineeringPerformanceAgent",
    "PRQualityScorerAgent",
    "CodeStandardizerAgent",
    "APIDriftDetectorAgent",
    "LogAnomalyScannerAgent",
    "AutoTestGeneratorAgent",
    "DocumentationCompletenessAgent",
    "UnusedCodeDetectorAgent",
    "ModuleDecomposerAgent",
    "JSONSchemaValidatorAgent",
    "DuplicateIssueDetectorAgent",
    # Testing & Performance Agents (17)
    "CommentImproverAgent",
    "ErrorCodeGeneratorAgent",
    "SQLInjectionAuditorAgent",
    "QueryOptimizerAgent",
    "BuildFailureAnalyzerAgent",
    "CachingConfigOptimizerAgent",
    "BreakingChangeDetectorAgent",
    "SpaghettiCodeRefactorAgent",
    "DeprecatedLibraryDetectorAgent",
    "DebugCodeRemoverAgent",
    "APIMockGeneratorAgent",
    "PaginationValidatorAgent",
    "AccessibilityAuditorAgent",
    "ReRenderOptimizerAgent",
    "BundleOptimizerAgent",
    "MemoryLeakDetectorAgent",
    "UnusedCSSDetectorAgent",
    # Analytics & Workflow Agents (24)
    "HealthMonitorAgent",
    "ErrorRateMonitorAgent",
    "PerformanceMetricsAgent",
    "UserBehaviorAnalyticsAgent",
    "UsageStatisticsAgent",
    "CIPipelineMonitorAgent",
    "TestCoverageAgent",
    "DeploymentSafetyAgent",
    "DependencyUpdaterAgent",
    "LintEnforcerAgent",
    "TypeCheckValidatorAgent",
    "SecurityScannerAgent",
    "DocumentationAuditorAgent",
    "CodeReviewAgent",
    "MergeSafetyAgent",
    "ReleaseValidatorAgent",
    "BackupAgent",
    "ScalabilityAnalyzerAgent",
    "IncidentResponseAgent",
    "SLAMonitorAgent",
    "TestDataGeneratorAgent",
    "APITestingAgent",
    "UITestingAgent",
    "LoadTestingAgent",
    # Specialized Agents (20)
    "SecurityHeaderValidatorAgent",
    "EncryptionStrategyAgent",
    "ThirdPartyScriptSafetyAgent",
    "CodingStyleEnforcerAgent",
    "LocalizationGapDetectorAgent",
    "PerformanceRegressionAgent",
    "SlowEndpointTrackerAgent",
    "UXFrictionTrackerAgent",
    "EnvironmentConfigDetectorAgent",
    "UptimeMonitorAgent",
    "IncidentMitigationPlannerAgent",
    "ReleaseNotesGeneratorAgent",
    "DependencyUpdaterAgentV2",
    "PRToJiraMapperAgent",
    "TestCoverageReporterAgent",
    "PermissionGapDetectorAgent",
    "WeeklyStabilityScorerAgent",
    "ArchitectureDriftDetectorAgent",
    "BugEnvironmentCreatorAgent",
    "RefactoringTargetProposerAgent",
]

# Version info
__version__ = "2.0.0"
__author__ = "PsychSync AI Team"
TOTAL_AGENTS = 74
